/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\MinGW\bin\gcc.exe -c  -w  -IC:\nim-0.16.0\lib -o c:\Projects\nim\HelloWorld\nimcache\nimFile.o c:\Projects\nim\HelloWorld\nimcache\nimFile.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(NCSTRING, TY_Kjizo4DRb4hVvUbJGvd4SQ) (void);
typedef N_NIMCALL_PTR(NCSTRING, TY_hALBovV7ZeOLQZyXZqNooQ) (NCSTRING name0);
N_NIMCALL(void*, loadlib_EFK1MHQsQvQPg5NaJH389bA)(NimStringDesc* path0, NIM_BOOL globalsymbols0);
N_NIMCALL(void*, symaddr_fM7lTRTvv9a9axreJA2Bx7jA_2)(void* lib0, NCSTRING name0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, nimFileDatInit000)(void);
void* liblibfoo_VIG7t7guw3ui7HBW6MAUtg;
void* ptrsayhelloworld_2wL9bhaX39cevo3XCQseoR9ag;
TY_Kjizo4DRb4hVvUbJGvd4SQ execsayhelloworld_5h9c4nDem7XFHhCSxKnT9c7w;
void* ptrgreet_Jk9aaSF6ZOFwthbM5frWdGw;
TY_hALBovV7ZeOLQZyXZqNooQ execgreet_vB1D78LBHRbkU9bzWJfUx7Q;
void* liblibfoo1_V4xn7OPvnxw1UBUxSrt5Tw;
void* ptrsayhelloworld1_rPtLGq9a7En25GosmF33gaw;
TY_Kjizo4DRb4hVvUbJGvd4SQ execsayhelloworld1_AAU9awj7c9bi2lC4qzIQxQew;
void* ptrgreet1_X9cxpAaOGQpxHA8BmjeuRDA;
TY_hALBovV7ZeOLQZyXZqNooQ execgreet1_r8sK9ce3OD39bAgov3s9cMygQ;
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(T_rE66HNSlIbRBxIg4CWWYqA_2, "libfoo.dll", 10);
STRING_LITERAL(T_rE66HNSlIbRBxIg4CWWYqA_3, "libfoo1.dll", 11);

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	nimFileDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr("nimFile", "nimFile.nim")
	nimln(5, "nimFile.nim");
	liblibfoo_VIG7t7guw3ui7HBW6MAUtg = loadlib_EFK1MHQsQvQPg5NaJH389bA(((NimStringDesc*) &T_rE66HNSlIbRBxIg4CWWYqA_2), NIM_FALSE);
	nimln(6, "nimFile.nim");
	{
		nimln(347, "system.nim");
		nimln(6, "nimFile.nim");
		if (!!((liblibfoo_VIG7t7guw3ui7HBW6MAUtg == NIM_NIL))) goto LA3;
		nimln(7, "nimFile.nim");
		ptrsayhelloworld_2wL9bhaX39cevo3XCQseoR9ag = symaddr_fM7lTRTvv9a9axreJA2Bx7jA_2(liblibfoo_VIG7t7guw3ui7HBW6MAUtg, "sayHelloWorld");
		nimln(8, "nimFile.nim");
		execsayhelloworld_5h9c4nDem7XFHhCSxKnT9c7w = ((TY_Kjizo4DRb4hVvUbJGvd4SQ) (ptrsayhelloworld_2wL9bhaX39cevo3XCQseoR9ag));
		nimln(9, "nimFile.nim");
		ptrgreet_Jk9aaSF6ZOFwthbM5frWdGw = symaddr_fM7lTRTvv9a9axreJA2Bx7jA_2(liblibfoo_VIG7t7guw3ui7HBW6MAUtg, "greet");
		nimln(10, "nimFile.nim");
		execgreet_vB1D78LBHRbkU9bzWJfUx7Q = ((TY_hALBovV7ZeOLQZyXZqNooQ) (ptrgreet_Jk9aaSF6ZOFwthbM5frWdGw));
	}
	LA3: ;
	nimln(13, "nimFile.nim");
	liblibfoo1_V4xn7OPvnxw1UBUxSrt5Tw = loadlib_EFK1MHQsQvQPg5NaJH389bA(((NimStringDesc*) &T_rE66HNSlIbRBxIg4CWWYqA_3), NIM_FALSE);
	nimln(14, "nimFile.nim");
	{
		nimln(347, "system.nim");
		nimln(14, "nimFile.nim");
		if (!!((liblibfoo1_V4xn7OPvnxw1UBUxSrt5Tw == NIM_NIL))) goto LA7;
		nimln(15, "nimFile.nim");
		ptrsayhelloworld1_rPtLGq9a7En25GosmF33gaw = symaddr_fM7lTRTvv9a9axreJA2Bx7jA_2(liblibfoo1_V4xn7OPvnxw1UBUxSrt5Tw, "sayHelloWorld1");
		nimln(16, "nimFile.nim");
		execsayhelloworld1_AAU9awj7c9bi2lC4qzIQxQew = ((TY_Kjizo4DRb4hVvUbJGvd4SQ) (ptrsayhelloworld1_rPtLGq9a7En25GosmF33gaw));
		nimln(17, "nimFile.nim");
		ptrgreet1_X9cxpAaOGQpxHA8BmjeuRDA = symaddr_fM7lTRTvv9a9axreJA2Bx7jA_2(liblibfoo1_V4xn7OPvnxw1UBUxSrt5Tw, "greet1");
		nimln(18, "nimFile.nim");
		execgreet1_r8sK9ce3OD39bAgov3s9cMygQ = ((TY_hALBovV7ZeOLQZyXZqNooQ) (ptrgreet1_X9cxpAaOGQpxHA8BmjeuRDA));
	}
	LA7: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimFileDatInit000)(void) {
}

