/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\MinGW\bin\gcc.exe -c  -w  -IC:\nim-0.16.0\lib -o c:\Projects\nim\HelloWorld\nimcache\stdlib_nativesockets.o c:\Projects\nim\HelloWorld\nimcache\stdlib_nativesockets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "winsock2.h"
#include <string.h>
#include "ws2tcpip.h"
#undef linux
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ;
typedef struct Servent_9ak3HAuy7nXhXlidAanTkdQ Servent_9ak3HAuy7nXhXlidAanTkdQ;
typedef struct Servent_uHHxGv5hdkoXDHlVaUxvnA Servent_uHHxGv5hdkoXDHlVaUxvnA;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct Hostent_azV1qb29cFIFe582aezrNAQ Hostent_azV1qb29cFIFe582aezrNAQ;
typedef struct Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw;
typedef struct TY_J0FzjuY02DFObU1sQZLwJA TY_J0FzjuY02DFObU1sQZLwJA;
typedef struct Timeval_9boMTr1l3P8e1j9aAjdqsQtA Timeval_9boMTr1l3P8e1j9aAjdqsQtA;
typedef struct Tfdset_lYo1mv6gU9aT1ZE1etM9ceog Tfdset_lYo1mv6gU9aT1ZE1etM9ceog;
typedef struct TY_qwqHTkRvwhrRyENtudHQ7g TY_qwqHTkRvwhrRyENtudHQ7g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(int, TY_awTV7srwWeJ9cGPOCgBQa7g) (NI s0, long cmd0, long* argptr0);
typedef NU8 Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 Socktype_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 Protocol_dqJ1OqRGclxIMMdSLRzzXg;
typedef N_STDCALL_PTR(NI, TY_9aO2cP4IgwjXF8JfUR57CHQ) (int af0, int typ0, int protocol0);
typedef N_STDCALL_PTR(int, TY_IQbFr9cLT9bipWCXYfwYwjOw) (NI s0);
typedef N_STDCALL_PTR(int, TY_T129bsPZ4FvuSF4rGFSBKkg) (NI s0, SOCKADDR* name0, unsigned int namelen0);
typedef N_STDCALL_PTR(int, TY_wy9bpl6t1mtPtDWeg0xLpDA) (NI s0, int backlog0);
struct  Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ  {
int aiflags;
int aifamily;
int aisocktype;
int aiprotocol;
NI aiaddrlen;
NCSTRING aicanonname;
SOCKADDR* aiaddr;
Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ* ainext;
};
typedef N_STDCALL_PTR(int, TY_MvjKU9c5nvs0N3IrS4vNgSw) (NCSTRING nodename0, NCSTRING servname0, Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ* hints0, Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ** res0);
typedef N_STDCALL_PTR(void, TY_IV3cwg4tBg3JP8ITSKt7oQ) (Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ* ai0);
typedef N_STDCALL_PTR(Servent_uHHxGv5hdkoXDHlVaUxvnA*, TY_E0SwAAX9bj9a9aV7n5MiMKzig) (NCSTRING name0, NCSTRING proto0);
struct  Servent_9ak3HAuy7nXhXlidAanTkdQ  {
NimStringDesc* name;
TY_sM4lkSb7zS6F7OVMvW9cffQ* aliases;
NU16 port;
NimStringDesc* proto;
};
struct  Servent_uHHxGv5hdkoXDHlVaUxvnA  {
NCSTRING sname;
NCSTRING* saliases;
NCSTRING sproto;
NI16 sport;
};
typedef N_STDCALL_PTR(Servent_uHHxGv5hdkoXDHlVaUxvnA*, TY_M3E1eZF9azJd5WrGSHMqEDA) (int port0, NCSTRING proto0);
typedef N_STDCALL_PTR(NU32, TY_jPIQsVcE09cbsdBUbAUxTCQ) (NCSTRING cp0);
typedef N_STDCALL_PTR(Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw*, TY_oU4d9cTB9cxBBS1maSQYgLMA) (IN_ADDR* ip0, unsigned int len0, int thetype0);
struct  Hostent_azV1qb29cFIFe582aezrNAQ  {
NimStringDesc* name;
TY_sM4lkSb7zS6F7OVMvW9cffQ* aliases;
Domain_Q79bEtFARvq0ekDNtvj3Vqg addrtype;
NI length;
TY_sM4lkSb7zS6F7OVMvW9cffQ* addrlist;
};
struct  Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw  {
NCSTRING hname;
NCSTRING* haliases;
NI16 haddrtype;
NI16 hlength;
NCSTRING* haddrlist;
};
typedef N_STDCALL_PTR(Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw*, TY_sUmKECsDIMWXpmy9a1Mqegg) (NCSTRING name0);
typedef NIM_CHAR TY_NSMq3FMCIrS8gSbyinBZ8w[14];
typedef N_STDCALL_PTR(int, TY_VXEvL0NvawmzSZzsbIHW6Q) (NI s0, SOCKADDR* name0, unsigned int* namelen0);
typedef N_STDCALL_PTR(NCSTRING, TY_MgrHyJlVVXQLRahsT9c14gQ) (IN_ADDR i0);
typedef NIM_CHAR TY_1NlJ8ipZDU6GZ9bDFAyQjfQ[8];
struct TY_J0FzjuY02DFObU1sQZLwJA {
NimStringDesc* Field0;
NU16 Field1;
};
typedef NIM_CHAR TY_Wfh9bjgBQ4UqJsyISUuDSuA[16];
typedef NIM_CHAR TY_2cWMSJoP9cqN4yIK0ILkQaQ[64];
typedef N_STDCALL_PTR(int, TY_smMaEORdTTSo9bCzv0g049aQ) (NI s0, int level0, int optname0, void* optval0, unsigned int* optlen0);
typedef N_STDCALL_PTR(int, TY_K6tJduk9ckQgneh7oD8F4Bg) (NI s0, int level0, int optname0, void* optval0, unsigned int optlen0);
struct  Timeval_9boMTr1l3P8e1j9aAjdqsQtA  {
NI32 tvsec;
NI32 tvusec;
};
typedef NI TY_SLBTEB08vk46ttuRaTxAYw[64];
struct  Tfdset_lYo1mv6gU9aT1ZE1etM9ceog  {
int fdcount;
TY_SLBTEB08vk46ttuRaTxAYw fdarray;
};
typedef N_STDCALL_PTR(int, TY_rWrG4X5lbcXQyLNkF9aNWhQ) (int nfds0, Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* readfds0, Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* writefds0, Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* exceptfds0, Timeval_9boMTr1l3P8e1j9aAjdqsQtA* timeout0);
typedef NIM_CHAR TY_EWK8XzFKXCg2WflN3ijhqA[257];
typedef NIM_CHAR TY_4249al09aeC68W9cvqMnjIYOA[129];
typedef N_STDCALL_PTR(int, TY_As5z9bYt859cLKWaorPRgQYA) (NI16 wversionrequired0, WSADATA* Wsdata0);
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path0);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path0);
N_NIMCALL(void*, nimGetProcAddr)(void* lib0, NCSTRING name0);
N_NIMCALL(int, toint_29b6Wz7Ivpqkf5L9boKDBoAg)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(int, toint_8FqW9bXNjjJADB8XlKnpNLg)(Socktype_NQT1bItGG2X9byGdrWX7ujw typ0);
N_NIMCALL(int, toint_9cDpnbeIxivYaLcJBJkQ2nQ)(Protocol_dqJ1OqRGclxIMMdSLRzzXg p0);
N_NIMCALL(NI, newnativesocket_WULFLawkclq9cew9bKzcJn4w)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, Socktype_NQT1bItGG2X9byGdrWX7ujw socktype0, Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol0);
N_NIMCALL(NI, newnativesocket_3upU1a4YiumYk2g5YvqfSA)(int domain0, int socktype0, int protocol0);
N_NIMCALL(void, close_gkrint1G7N0tDyL9b6wUJug)(NI socket0);
N_NIMCALL(int, bindaddr_2tQ5L6urT7QbAhZLRP4TBA)(NI socket0, SOCKADDR* name0, unsigned int namelen0);
N_NIMCALL(int, listen_x9cO0dJiBh5DSfILBu5u9caQ)(NI socket0, int backlog0);
N_NIMCALL(Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ*, getaddrinfo_oJYXw9a6xiOxTxda6sTTRJg)(NimStringDesc* address0, NU16 port0, Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, Socktype_NQT1bItGG2X9byGdrWX7ujw socktype0, Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol0);
N_NIMCALL(NimStringDesc*, HEX24_rzAI8EMyNBAQwGODeohhAA)(NU64 x0);
N_NOINLINE(void, raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA)(NI32 errorcode0, NimStringDesc* additionalinfo0);
N_NIMCALL(NI32, oslasterror_6wyvsbJUteIgEY9cC5BVJZQ)(void);
N_NIMCALL(void, dealloc_CDSQIIFHQ4ElQ1Lt6BJuEg)(Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ* ai0);
N_NIMCALL(NU32, ntohl_RStKcIp64i7w9c4KBI2z46w)(NU32 x0);
N_NIMCALL(NU16, ntohs_hTWZ9cGeQnQNEThS6k8qUKg)(NU16 x0);
N_NIMCALL(void, getservbyname_CbLPGzG25vLA69bCp9c8vUGg)(NimStringDesc* name0, NimStringDesc* proto0, Servent_9ak3HAuy7nXhXlidAanTkdQ* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, cstringarraytoseq_4PY1a5GnAxjeKfScivCuQw)(NCSTRING* a0);
N_NIMCALL(void, getservbyport_ArkrSwAitAfuTL9a9cpcTIhQ)(NU16 port0, NimStringDesc* proto0, Servent_9ak3HAuy7nXhXlidAanTkdQ* Result);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void, gethostbyaddr_thIyCshVWqmin8xsxY5Tvw)(NimStringDesc* ip0, Hostent_azV1qb29cFIFe582aezrNAQ* Result);
N_NIMCALL(void, gethostbyname_GtLhLbA2rADAuSXSXBQ09aQ)(NimStringDesc* name0, Hostent_azV1qb29cFIFe582aezrNAQ* Result);
N_NIMCALL(Domain_Q79bEtFARvq0ekDNtvj3Vqg, getsockdomain_gCpH59bOpIMSgBk8rXR8mkg)(NI socket0);
N_NIMCALL(NimStringDesc*, getaddrstring_Pd7Ci2fnS9aN410185y1XSg)(SOCKADDR* sockaddr0);
N_NIMCALL(NU16, getsockname_vpdzNZNuSiYK8ffxz4poBQ)(NI socket0);
N_NIMCALL(void, getlocaladdr_SFe3BSsng27mHF9ca7VrxLA)(NI socket0, Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, TY_J0FzjuY02DFObU1sQZLwJA* Result);
N_STDCALL(NCSTRING, inetntop_ClwlBFBvPryllhRtGuXdLw)(int family0, void* paddr0, NCSTRING pstringbuffer0, NI32 stringbufsize0);
N_NIMCALL(void, getpeeraddr_SFe3BSsng27mHF9ca7VrxLA_2)(NI socket0, Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, TY_J0FzjuY02DFObU1sQZLwJA* Result);
N_NIMCALL(NI, getsockoptint_Bcy79aVO5nZ0AND6B1KoG4g)(NI socket0, NI level0, NI optname0);
N_NIMCALL(void, setsockoptint_Q4lBY4MFWt3Wx9bU5oC8TvA)(NI socket0, NI level0, NI optname0, NI optval0);
N_NIMCALL(void, setblocking_HDkmwGOArLmNmxp9c5tG9c9cw)(NI s0, NIM_BOOL blocking0);
N_NIMCALL(Timeval_9boMTr1l3P8e1j9aAjdqsQtA, timevalfrommilliseconds_8n6ccdvLo6VgMVggcNy9bzw)(NI timeout0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(void, createfdset_Uq0gtMrL5zwaOYtdZK68kg)(Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* fd0, TY_qwqHTkRvwhrRyENtudHQ7g* s0, NI* m0);
N_NIMCALL(void, Fdzero_yeePfMmq9aNgPmxq9aV4wa4A)(Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* s0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, Fdset_RyfVGaM8zBlYSZOQ5CvEEQ)(NI socket0, Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* s0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
N_NIMCALL(void, prunesocketset_70Zyypm1k20h9c9bjjAUrOmw)(TY_qwqHTkRvwhrRyENtudHQ7g** s0, Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* fd0);
N_NIMCALL(int, Fdisset_NkjjeLx4p9b4GT29buKQYcxA)(NI socket0, Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* set0);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq0, NI elemsize0, NI newlen0);
N_NIMCALL(NI, select_eXjloAphe9a2xyF9bVEutDXA)(TY_qwqHTkRvwhrRyENtudHQ7g** readfds0, NI timeout0);
N_NIMCALL(NI, selectwrite_Xl49alpuj6Qo9brq9cgUHYNlQ)(TY_qwqHTkRvwhrRyENtudHQ7g** writefds0, NI timeout0);
NI osinvalidsocket_voz9aUXu8jtRbvGZZJHNE8w;
static void* T_f9bP3LqjpgpB9cXL8Nnak7tQ_2;
TY_awTV7srwWeJ9cGPOCgBQa7g Dl_163681;
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TY_9aO2cP4IgwjXF8JfUR57CHQ Dl_129397;
extern TY_IQbFr9cLT9bipWCXYfwYwjOw Dl_129402;
extern TY_T129bsPZ4FvuSF4rGFSBKkg Dl_129412;
extern TY_wy9bpl6t1mtPtDWeg0xLpDA Dl_129453;
extern TY_MvjKU9c5nvs0N3IrS4vNgSw Dl_129549;
extern TY_IV3cwg4tBg3JP8ITSKt7oQ Dl_129558;
extern TY_E0SwAAX9bj9a9aV7n5MiMKzig Dl_129376;
extern TY_M3E1eZF9azJd5WrGSHMqEDA Dl_129381;
extern TY_jPIQsVcE09cbsdBUbAUxTCQ Dl_129511;
extern TY_oU4d9cTB9cxBBS1maSQYgLMA Dl_129386;
extern TY_sUmKECsDIMWXpmy9a1Mqegg Dl_129393;
extern TY_VXEvL0NvawmzSZzsbIHW6Q Dl_129424;
extern TY_MgrHyJlVVXQLRahsT9c14gQ Dl_129562;
extern TY_VXEvL0NvawmzSZzsbIHW6Q Dl_129431;
extern TY_smMaEORdTTSo9bCzv0g049aQ Dl_129438;
extern TY_K6tJduk9ckQgneh7oD8F4Bg Dl_129446;
extern TY_rWrG4X5lbcXQyLNkF9aNWhQ Dl_129473;
WSADATA wsa_ClAT9bhT9cqG9adztamb5X9b2w;
extern TY_As5z9bYt859cLKWaorPRgQYA Dl_129544;
TNimType NTI_Q79bEtFARvq0ekDNtvj3Vqg;
TNimType NTI_NQT1bItGG2X9byGdrWX7ujw;
TNimType NTI_dqJ1OqRGclxIMMdSLRzzXg;
STRING_LITERAL(T_f9bP3LqjpgpB9cXL8Nnak7tQ_4, "ws2_32.dll", 10);
STRING_LITERAL(T_f9bP3LqjpgpB9cXL8Nnak7tQ_5, "ws2_32.dll", 10);
STRING_LITERAL(T_f9bP3LqjpgpB9cXL8Nnak7tQ_8, "", 0);
STRING_LITERAL(T_f9bP3LqjpgpB9cXL8Nnak7tQ_9, "Service not found.", 18);
STRING_LITERAL(T_f9bP3LqjpgpB9cXL8Nnak7tQ_10, "unknown socket family in getSockFamily", 38);
STRING_LITERAL(T_f9bP3LqjpgpB9cXL8Nnak7tQ_11, "unknown socket family in getAddrString", 38);
STRING_LITERAL(T_f9bP3LqjpgpB9cXL8Nnak7tQ_12, "invalid socket family in getLocalAddr", 37);
STRING_LITERAL(T_f9bP3LqjpgpB9cXL8Nnak7tQ_18, "len(a) == L seq modified while iterating over it", 48);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(int, toint_29b6Wz7Ivpqkf5L9boKDBoAg)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0) {
	int result0;
	nimfr("toInt", "nativesockets.nim")
	result0 = (int)0;
	nimln(151, "nativesockets.nim");
	result0 = ((int) (((NI16)(NU16)(NU)(((NI) (domain0))))));
	popFrame();
	return result0;
}

N_NIMCALL(int, toint_8FqW9bXNjjJADB8XlKnpNLg)(Socktype_NQT1bItGG2X9byGdrWX7ujw typ0) {
	int result0;
	nimfr("toInt", "nativesockets.nim")
	result0 = (int)0;
	nimln(154, "nativesockets.nim");
	result0 = ((int) (typ0));
	popFrame();
	return result0;
}

N_NIMCALL(int, toint_9cDpnbeIxivYaLcJBJkQ2nQ)(Protocol_dqJ1OqRGclxIMMdSLRzzXg p0) {
	int result0;
	nimfr("toInt", "nativesockets.nim")
	result0 = (int)0;
	nimln(157, "nativesockets.nim");
	result0 = ((int) (p0));
	popFrame();
	return result0;
}

N_NIMCALL(NI, newnativesocket_WULFLawkclq9cew9bKzcJn4w)(Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, Socktype_NQT1bItGG2X9byGdrWX7ujw socktype0, Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol0) {
	NI result0;
	int LOC1;
	int LOC2;
	int LOC3;
	nimfr("newNativeSocket", "nativesockets.nim")
	result0 = (NI)0;
	nimln(163, "nativesockets.nim");
	nimln(164, "nativesockets.nim");
	LOC1 = (int)0;
	LOC1 = toint_29b6Wz7Ivpqkf5L9boKDBoAg(domain0);
	LOC2 = (int)0;
	LOC2 = toint_8FqW9bXNjjJADB8XlKnpNLg(socktype0);
	LOC3 = (int)0;
	LOC3 = toint_9cDpnbeIxivYaLcJBJkQ2nQ(protocol0);
	result0 = Dl_129397(LOC1, LOC2, LOC3);
	popFrame();
	return result0;
}

N_NIMCALL(NI, newnativesocket_3upU1a4YiumYk2g5YvqfSA)(int domain0, int socktype0, int protocol0) {
	NI result0;
	nimfr("newNativeSocket", "nativesockets.nim")
	result0 = (NI)0;
	nimln(168, "nativesockets.nim");
	nimln(172, "nativesockets.nim");
	result0 = Dl_129397(domain0, socktype0, protocol0);
	popFrame();
	return result0;
}

N_NIMCALL(void, close_gkrint1G7N0tDyL9b6wUJug)(NI socket0) {
	int LOC1;
	nimfr("close", "nativesockets.nim")
	nimln(177, "nativesockets.nim");
	LOC1 = (int)0;
	LOC1 = Dl_129402(socket0);
	popFrame();
}

N_NIMCALL(int, bindaddr_2tQ5L6urT7QbAhZLRP4TBA)(NI socket0, SOCKADDR* name0, unsigned int namelen0) {
	int result0;
	nimfr("bindAddr", "nativesockets.nim")
	result0 = (int)0;
	nimln(184, "nativesockets.nim");
	result0 = Dl_129412(socket0, name0, namelen0);
	popFrame();
	return result0;
}

N_NIMCALL(int, listen_x9cO0dJiBh5DSfILBu5u9caQ)(NI socket0, int backlog0) {
	int result0;
	nimfr("listen", "nativesockets.nim")
	result0 = (int)0;
	nimln(191, "nativesockets.nim");
	result0 = Dl_129453(socket0, backlog0);
	popFrame();
	return result0;
}

N_NIMCALL(Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ*, getaddrinfo_oJYXw9a6xiOxTxda6sTTRJg)(NimStringDesc* address0, NU16 port0, Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, Socktype_NQT1bItGG2X9byGdrWX7ujw socktype0, Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol0) {
	Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ* result0;
	Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ hints0;
	int gairesult0;
	NimStringDesc* LOC5;
	nimfr("getAddrInfo", "nativesockets.nim")
	result0 = (Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ*)0;
	memset((void*)(&hints0), 0, sizeof(hints0));
	nimln(202, "nativesockets.nim");
	result0 = NIM_NIL;
	nimln(203, "nativesockets.nim");
	hints0.aifamily = toint_29b6Wz7Ivpqkf5L9boKDBoAg(domain0);
	nimln(204, "nativesockets.nim");
	hints0.aisocktype = toint_8FqW9bXNjjJADB8XlKnpNLg(socktype0);
	nimln(205, "nativesockets.nim");
	hints0.aiprotocol = toint_9cDpnbeIxivYaLcJBJkQ2nQ(protocol0);
	nimln(210, "nativesockets.nim");
	{
		if (!(domain0 == ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23))) goto LA3;
		nimln(211, "nativesockets.nim");
		hints0.aiflags = ((int) 8);
	}
	LA3: ;
	nimln(212, "nativesockets.nim");
	LOC5 = (NimStringDesc*)0;
	LOC5 = HEX24_rzAI8EMyNBAQwGODeohhAA(port0);
	gairesult0 = Dl_129549(address0->data, LOC5->data, (&hints0), &result0);
	nimln(213, "nativesockets.nim");
	{
		NI32 LOC10;
		nimln(347, "system.nim");
		nimln(213, "nativesockets.nim");
		if (!!((gairesult0 == ((NI32) 0)))) goto LA8;
		nimln(215, "nativesockets.nim");
		LOC10 = (NI32)0;
		LOC10 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC10, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA8: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, dealloc_CDSQIIFHQ4ElQ1Lt6BJuEg)(Addrinfo_C9ahX3gj0cVjII4vjiaSHBQ* ai0) {
	nimfr("dealloc", "nativesockets.nim")
	nimln(220, "nativesockets.nim");
	Dl_129558(ai0);
	popFrame();
}

N_NIMCALL(NU32, ntohl_RStKcIp64i7w9c4KBI2z46w)(NU32 x0) {
	NU32 result0;
	nimfr("ntohl", "nativesockets.nim")
	result0 = (NU32)0;
	nimln(227, "nativesockets.nim");
	nimln(228, "nativesockets.nim");
	nimln(227, "nativesockets.nim");
	nimln(228, "nativesockets.nim");
	nimln(229, "nativesockets.nim");
	nimln(230, "nativesockets.nim");
	result0 = (NU32)((NU32)((NU32)((NU32)((NU32)(x0) >> (NU32)(((NU32) 24))) | (NU32)((NU32)((NU32)(x0) >> (NU32)(((NU32) 8))) & ((NU32) 65280))) | (NU32)((NU32)((NU32)(x0) << (NU32)(((NU32) 8))) & ((NU32) 16711680))) | (NU32)((NU32)(x0) << (NU32)(((NU32) 24))));
	popFrame();
	return result0;
}

N_NIMCALL(NU16, ntohs_hTWZ9cGeQnQNEThS6k8qUKg)(NU16 x0) {
	NU16 result0;
	nimfr("ntohs", "nativesockets.nim")
	result0 = (NU16)0;
	nimln(246, "nativesockets.nim");
	result0 = (NU16)((NU16)((NU16)(x0) >> (NU16)(((NU16) 8))) | (NU16)((NU16)(x0) << (NU16)(((NU16) 8))));
	popFrame();
	return result0;
}

N_NIMCALL(void, getservbyname_CbLPGzG25vLA69bCp9c8vUGg)(NimStringDesc* name0, NimStringDesc* proto0, Servent_9ak3HAuy7nXhXlidAanTkdQ* Result) {
	Servent_uHHxGv5hdkoXDHlVaUxvnA* s0;
	nimfr("getServByName", "nativesockets.nim")
	nimln(294, "nativesockets.nim");
	s0 = Dl_129376(name0->data, proto0->data);
	nimln(297, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s0 == NIM_NIL)) goto LA3;
		LOC5 = (NI32)0;
		LOC5 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC5, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA3: ;
	nimln(298, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s0).sname));
	nimln(299, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_4PY1a5GnAxjeKfScivCuQw((*s0).saliases));
	nimln(300, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s0).sport));
	nimln(301, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s0).sproto));
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, getservbyport_ArkrSwAitAfuTL9a9cpcTIhQ)(NU16 port0, NimStringDesc* proto0, Servent_9ak3HAuy7nXhXlidAanTkdQ* Result) {
	Servent_uHHxGv5hdkoXDHlVaUxvnA* s0;
	nimfr("getServByPort", "nativesockets.nim")
	nimln(310, "nativesockets.nim");
	s0 = Dl_129381(((int)chckRange(((NI)(NU)(NU16)(((NI16)chckRange(port0, ((NI16) -32768), ((NI16) 32767))))), ((int) (-2147483647 -1)), ((int) 2147483647))), proto0->data);
	nimln(313, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s0 == NIM_NIL)) goto LA3;
		LOC5 = (NI32)0;
		LOC5 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC5, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA3: ;
	nimln(314, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s0).sname));
	nimln(315, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_4PY1a5GnAxjeKfScivCuQw((*s0).saliases));
	nimln(316, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s0).sport));
	nimln(317, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s0).sproto));
	popFrame();
}

N_NIMCALL(void, gethostbyaddr_thIyCshVWqmin8xsxY5Tvw)(NimStringDesc* ip0, Hostent_azV1qb29cFIFe582aezrNAQ* Result) {
	IN_ADDR myaddr0;
	Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw* s0;
	nimfr("getHostByAddr", "nativesockets.nim")
	memset((void*)(&myaddr0), 0, sizeof(myaddr0));
	nimln(322, "nativesockets.nim");
	myaddr0.s_addr = Dl_129511(ip0->data);
	nimln(325, "nativesockets.nim");
	s0 = Dl_129386((&myaddr0), ((unsigned int) (((NI)sizeof(IN_ADDR)))), ((int) 2));
	nimln(327, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s0 == NIM_NIL)) goto LA3;
		LOC5 = (NI32)0;
		LOC5 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC5, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA3: ;
	nimln(339, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s0).hname));
	nimln(340, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_4PY1a5GnAxjeKfScivCuQw((*s0).haliases));
	nimln(342, "nativesockets.nim");
	(*Result).addrtype = ((Domain_Q79bEtFARvq0ekDNtvj3Vqg)chckRange((*s0).haddrtype, ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0), ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23)));
	nimln(350, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrlist), cstringarraytoseq_4PY1a5GnAxjeKfScivCuQw((*s0).haddrlist));
	nimln(351, "nativesockets.nim");
	(*Result).length = ((NI) ((*s0).hlength));
	popFrame();
}

N_NIMCALL(void, gethostbyname_GtLhLbA2rADAuSXSXBQ09aQ)(NimStringDesc* name0, Hostent_azV1qb29cFIFe582aezrNAQ* Result) {
	Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw* s0;
	nimfr("getHostByName", "nativesockets.nim")
	nimln(356, "nativesockets.nim");
	s0 = Dl_129393(name0->data);
	nimln(359, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s0 == NIM_NIL)) goto LA3;
		LOC5 = (NI32)0;
		LOC5 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC5, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA3: ;
	nimln(360, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s0).hname));
	nimln(361, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_4PY1a5GnAxjeKfScivCuQw((*s0).haliases));
	nimln(363, "nativesockets.nim");
	(*Result).addrtype = ((Domain_Q79bEtFARvq0ekDNtvj3Vqg)chckRange((*s0).haddrtype, ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0), ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23)));
	nimln(371, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrlist), cstringarraytoseq_4PY1a5GnAxjeKfScivCuQw((*s0).haddrlist));
	nimln(372, "nativesockets.nim");
	(*Result).length = ((NI) ((*s0).hlength));
	popFrame();
}

N_NIMCALL(Domain_Q79bEtFARvq0ekDNtvj3Vqg, getsockdomain_gCpH59bOpIMSgBk8rXR8mkg)(NI socket0) {
	Domain_Q79bEtFARvq0ekDNtvj3Vqg result0;
	SOCKADDR name0;
	unsigned int namelen0;
	nimfr("getSockDomain", "nativesockets.nim")
	result0 = (Domain_Q79bEtFARvq0ekDNtvj3Vqg)0;
	memset((void*)(&name0), 0, sizeof(name0));
	nimln(377, "nativesockets.nim");
	namelen0 = ((unsigned int) (((NI)sizeof(SOCKADDR))));
	nimln(378, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		LOC3 = (int)0;
		LOC3 = Dl_129424(socket0, ((SOCKADDR*) ((&name0))), (&namelen0));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(380, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC6, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4: ;
	nimln(381, "nativesockets.nim");
	{
		if (!(name0.sa_family == ((NI16) 2))) goto LA9;
		nimln(382, "nativesockets.nim");
		result0 = ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2);
	}
	goto LA7;
	LA9: ;
	{
		nimln(383, "nativesockets.nim");
		if (!(name0.sa_family == ((NI16) 23))) goto LA12;
		nimln(384, "nativesockets.nim");
		result0 = ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23);
	}
	goto LA7;
	LA12: ;
	{
		NI32 LOC15;
		nimln(386, "nativesockets.nim");
		LOC15 = (NI32)0;
		LOC15 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC15, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_10));
	}
	LA7: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, getaddrstring_Pd7Ci2fnS9aN410185y1XSg)(SOCKADDR* sockaddr0) {
	NimStringDesc* result0;
	nimfr("getAddrString", "nativesockets.nim")
	result0 = (NimStringDesc*)0;
	nimln(391, "nativesockets.nim");
	{
		NCSTRING LOC5;
		if (!((*sockaddr0).sa_family == ((NI16) 2))) goto LA3;
		nimln(392, "nativesockets.nim");
		LOC5 = (NCSTRING)0;
		LOC5 = Dl_129562((*((SOCKADDR_IN*) (sockaddr0))).sin_addr);
		result0 = cstrToNimstr(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		nimln(393, "nativesockets.nim");
		if (!((*sockaddr0).sa_family == ((NI16) 23))) goto LA7;
	}
	goto LA1;
	LA7: ;
	{
		NI32 LOC10;
		nimln(403, "nativesockets.nim");
		LOC10 = (NI32)0;
		LOC10 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC10, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NU16, getsockname_vpdzNZNuSiYK8ffxz4poBQ)(NI socket0) {
	NU16 result0;
	SOCKADDR_IN name0;
	unsigned int namelen0;
	nimfr("getSockName", "nativesockets.nim")
	result0 = (NU16)0;
	memset((void*)(&name0), 0, sizeof(name0));
	nimln(410, "nativesockets.nim");
	name0.sin_family = ((NI16) 2);
	nimln(415, "nativesockets.nim");
	namelen0 = ((unsigned int) (((NI)sizeof(SOCKADDR_IN))));
	nimln(416, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		LOC3 = (int)0;
		LOC3 = Dl_129424(socket0, ((SOCKADDR*) ((&name0))), (&namelen0));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(418, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC6, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4: ;
	nimln(419, "nativesockets.nim");
	result0 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name0.sin_port);
	popFrame();
	return result0;
}

N_NIMCALL(void, getlocaladdr_SFe3BSsng27mHF9ca7VrxLA)(NI socket0, Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, TY_J0FzjuY02DFObU1sQZLwJA* Result) {
	nimfr("getLocalAddr", "nativesockets.nim")
	nimln(425, "nativesockets.nim");
	switch (domain0) {
	case ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		SOCKADDR_IN name0;
		unsigned int namelen0;
		NCSTRING LOC8;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(429, "nativesockets.nim");
		name0.sin_family = ((NI16) 2);
		nimln(432, "nativesockets.nim");
		namelen0 = ((unsigned int) (((NI)sizeof(SOCKADDR_IN))));
		nimln(433, "nativesockets.nim");
		{
			int LOC4;
			NI32 LOC7;
			LOC4 = (int)0;
			LOC4 = Dl_129424(socket0, ((SOCKADDR*) ((&name0))), (&namelen0));
			if (!(LOC4 == ((NI32) -1))) goto LA5;
			nimln(435, "nativesockets.nim");
			LOC7 = (NI32)0;
			LOC7 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
			raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC7, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA5: ;
		nimln(436, "nativesockets.nim");
		LOC8 = (NCSTRING)0;
		LOC8 = Dl_129562(name0.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(LOC8));
		nimln(437, "nativesockets.nim");
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name0.sin_port);
	}
	break;
	case ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23):
	{
		SOCKADDR_IN6 name0;
		unsigned int namelen0;
		TY_2cWMSJoP9cqN4yIK0ILkQaQ buf0;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(441, "nativesockets.nim");
		name0.sin6_family = ((NI16) 23);
		nimln(444, "nativesockets.nim");
		namelen0 = ((unsigned int) (((NI)sizeof(SOCKADDR_IN6))));
		nimln(445, "nativesockets.nim");
		{
			int LOC12;
			NI32 LOC15;
			LOC12 = (int)0;
			LOC12 = Dl_129424(socket0, ((SOCKADDR*) ((&name0))), (&namelen0));
			if (!(LOC12 == ((NI32) -1))) goto LA13;
			nimln(447, "nativesockets.nim");
			LOC15 = (NI32)0;
			LOC15 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
			raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC15, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA13: ;
		memset((void*)buf0, 0, sizeof(buf0));
		nimln(450, "nativesockets.nim");
		{
			NCSTRING LOC18;
			NI32 LOC21;
			nimln(451, "nativesockets.nim");
			LOC18 = (NCSTRING)0;
			LOC18 = inetntop_ClwlBFBvPryllhRtGuXdLw(((int) (name0.sin6_family)), ((void*) ((&name0))), ((NCSTRING) (buf0)), ((NI32)chckRange(((NI)sizeof(TY_2cWMSJoP9cqN4yIK0ILkQaQ)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!(LOC18 == 0)) goto LA19;
			nimln(452, "nativesockets.nim");
			LOC21 = (NI32)0;
			LOC21 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
			raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC21, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA19: ;
		nimln(453, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf0))));
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name0.sin6_port);
	}
	break;
	default:
	{
		nimln(455, "nativesockets.nim");
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(((NI32) -1), ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_12));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(void, getpeeraddr_SFe3BSsng27mHF9ca7VrxLA_2)(NI socket0, Domain_Q79bEtFARvq0ekDNtvj3Vqg domain0, TY_J0FzjuY02DFObU1sQZLwJA* Result) {
	nimfr("getPeerAddr", "nativesockets.nim")
	nimln(461, "nativesockets.nim");
	switch (domain0) {
	case ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		SOCKADDR_IN name0;
		unsigned int namelen0;
		NCSTRING LOC8;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(465, "nativesockets.nim");
		name0.sin_family = ((NI16) 2);
		nimln(468, "nativesockets.nim");
		namelen0 = ((unsigned int) (((NI)sizeof(SOCKADDR_IN))));
		nimln(469, "nativesockets.nim");
		{
			int LOC4;
			NI32 LOC7;
			LOC4 = (int)0;
			LOC4 = Dl_129431(socket0, ((SOCKADDR*) ((&name0))), (&namelen0));
			if (!(LOC4 == ((NI32) -1))) goto LA5;
			nimln(471, "nativesockets.nim");
			LOC7 = (NI32)0;
			LOC7 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
			raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC7, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA5: ;
		nimln(472, "nativesockets.nim");
		LOC8 = (NCSTRING)0;
		LOC8 = Dl_129562(name0.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(LOC8));
		nimln(473, "nativesockets.nim");
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name0.sin_port);
	}
	break;
	case ((Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23):
	{
		SOCKADDR_IN6 name0;
		unsigned int namelen0;
		TY_2cWMSJoP9cqN4yIK0ILkQaQ buf0;
		memset((void*)(&name0), 0, sizeof(name0));
		nimln(477, "nativesockets.nim");
		name0.sin6_family = ((NI16) 23);
		nimln(480, "nativesockets.nim");
		namelen0 = ((unsigned int) (((NI)sizeof(SOCKADDR_IN6))));
		nimln(481, "nativesockets.nim");
		{
			int LOC12;
			NI32 LOC15;
			LOC12 = (int)0;
			LOC12 = Dl_129431(socket0, ((SOCKADDR*) ((&name0))), (&namelen0));
			if (!(LOC12 == ((NI32) -1))) goto LA13;
			nimln(483, "nativesockets.nim");
			LOC15 = (NI32)0;
			LOC15 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
			raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC15, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA13: ;
		memset((void*)buf0, 0, sizeof(buf0));
		nimln(486, "nativesockets.nim");
		{
			NCSTRING LOC18;
			NI32 LOC21;
			nimln(487, "nativesockets.nim");
			LOC18 = (NCSTRING)0;
			LOC18 = inetntop_ClwlBFBvPryllhRtGuXdLw(((int) (name0.sin6_family)), ((void*) ((&name0))), ((NCSTRING) (buf0)), ((NI32)chckRange(((NI)sizeof(TY_2cWMSJoP9cqN4yIK0ILkQaQ)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!(LOC18 == 0)) goto LA19;
			nimln(488, "nativesockets.nim");
			LOC21 = (NI32)0;
			LOC21 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
			raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC21, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA19: ;
		nimln(489, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf0))));
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name0.sin6_port);
	}
	break;
	default:
	{
		nimln(491, "nativesockets.nim");
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(((NI32) -1), ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_12));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NI, getsockoptint_Bcy79aVO5nZ0AND6B1KoG4g)(NI socket0, NI level0, NI optname0) {
	NI result0;
	int res0;
	unsigned int size0;
	nimfr("getSockOptInt", "nativesockets.nim")
	result0 = (NI)0;
	res0 = (int)0;
	nimln(497, "nativesockets.nim");
	size0 = ((unsigned int) 4);
	nimln(498, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		LOC3 = (int)0;
		LOC3 = Dl_129438(socket0, ((int)chckRange(level0, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname0, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&res0))), (&size0));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(500, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC6, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4: ;
	nimln(501, "nativesockets.nim");
	result0 = ((NI) (res0));
	popFrame();
	return result0;
}

N_NIMCALL(void, setsockoptint_Q4lBY4MFWt3Wx9bU5oC8TvA)(NI socket0, NI level0, NI optname0, NI optval0) {
	int value0;
	nimfr("setSockOptInt", "nativesockets.nim")
	nimln(506, "nativesockets.nim");
	value0 = ((int)chckRange(optval0, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln(507, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		LOC3 = (int)0;
		LOC3 = Dl_129446(socket0, ((int)chckRange(level0, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname0, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&value0))), ((unsigned int) 4));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(509, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC6, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, setblocking_HDkmwGOArLmNmxp9c5tG9c9cw)(NI s0, NIM_BOOL blocking0) {
	long mode0;
	nimfr("setBlocking", "nativesockets.nim")
	nimln(516, "nativesockets.nim");
	mode0 = ((long) (!(blocking0)));
	nimln(517, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		LOC3 = (int)0;
		LOC3 = Dl_163681(s0, ((NI32) -2147195266), (&mode0));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(518, "nativesockets.nim");
		LOC6 = (NI32)0;
		LOC6 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC6, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Timeval_9boMTr1l3P8e1j9aAjdqsQtA, timevalfrommilliseconds_8n6ccdvLo6VgMVggcNy9bzw)(NI timeout0) {
	Timeval_9boMTr1l3P8e1j9aAjdqsQtA result0;
	nimfr("timeValFromMilliseconds", "nativesockets.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(529, "nativesockets.nim");
	{
		NI seconds0;
		NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_13;
		NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_14;
		NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_15;
		NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_16;
		nimln(347, "system.nim");
		nimln(529, "nativesockets.nim");
		if (!!((timeout0 == ((NI) -1)))) goto LA3;
		nimln(530, "nativesockets.nim");
		T_f9bP3LqjpgpB9cXL8Nnak7tQ_13 = divInt(timeout0, ((NI) 1000));
		seconds0 = (NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_13);
		nimln(531, "nativesockets.nim");
		result0.tvsec = ((NI32)chckRange(seconds0, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		nimln(532, "nativesockets.nim");
		T_f9bP3LqjpgpB9cXL8Nnak7tQ_14 = mulInt(seconds0, ((NI) 1000));
		T_f9bP3LqjpgpB9cXL8Nnak7tQ_15 = subInt(timeout0, (NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_14));
		T_f9bP3LqjpgpB9cXL8Nnak7tQ_16 = mulInt((NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_15), ((NI) 1000));
		result0.tvusec = ((NI32)chckRange((NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_16), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	}
	LA3: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, createfdset_Uq0gtMrL5zwaOYtdZK68kg)(Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* fd0, TY_qwqHTkRvwhrRyENtudHQ7g* s0, NI* m0) {
	nimfr("createFdSet", "nativesockets.nim")
	nimln(535, "nativesockets.nim");
	Fdzero_yeePfMmq9aNgPmxq9aV4wa4A(fd0);
	{
		NI i_nWrf6GGpi6kMSu48P1sdpQ;
		NI i_nWrf6GGpi6kMSu48P1sdpQ_2;
		NI L_lAnPRRLtA1UXwDUiJslUqA;
		i_nWrf6GGpi6kMSu48P1sdpQ = (NI)0;
		nimln(3497, "system.nim");
		i_nWrf6GGpi6kMSu48P1sdpQ_2 = ((NI) 0);
		nimln(3498, "system.nim");
		nimln(536, "nativesockets.nim");
		L_lAnPRRLtA1UXwDUiJslUqA = (s0 ? s0->Sup.len : 0);
		{
			nimln(3499, "system.nim");
			while (1) {
				NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_17;
				nimln(3497, "system.nim");
				if (!(i_nWrf6GGpi6kMSu48P1sdpQ_2 < L_lAnPRRLtA1UXwDUiJslUqA)) goto LA3;
				nimln(3500, "system.nim");
				if ((NU)(i_nWrf6GGpi6kMSu48P1sdpQ_2) >= (NU)(s0->Sup.len)) raiseIndexError();
				i_nWrf6GGpi6kMSu48P1sdpQ = s0->data[i_nWrf6GGpi6kMSu48P1sdpQ_2];
				nimln(537, "nativesockets.nim");
				(*m0) = (((*m0) >= i_nWrf6GGpi6kMSu48P1sdpQ) ? (*m0) : i_nWrf6GGpi6kMSu48P1sdpQ);
				nimln(538, "nativesockets.nim");
				Fdset_RyfVGaM8zBlYSZOQ5CvEEQ(i_nWrf6GGpi6kMSu48P1sdpQ, fd0);
				nimln(3497, "system.nim");
				T_f9bP3LqjpgpB9cXL8Nnak7tQ_17 = addInt(i_nWrf6GGpi6kMSu48P1sdpQ_2, ((NI) 1));
				i_nWrf6GGpi6kMSu48P1sdpQ_2 = (NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_17);
				nimln(3502, "system.nim");
				{
					nimln(536, "nativesockets.nim");
					if (!!(((s0 ? s0->Sup.len : 0) == L_lAnPRRLtA1UXwDUiJslUqA))) goto LA6;
					nimln(3502, "system.nim");
					failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_18));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, prunesocketset_70Zyypm1k20h9c9bjjAUrOmw)(TY_qwqHTkRvwhrRyENtudHQ7g** s0, Tfdset_lYo1mv6gU9aT1ZE1etM9ceog* fd0) {
	NI i0;
	NI L0;
	nimfr("pruneSocketSet", "nativesockets.nim")
	nimln(541, "nativesockets.nim");
	i0 = ((NI) 0);
	nimln(542, "nativesockets.nim");
	L0 = ((*s0) ? (*s0)->Sup.len : 0);
	{
		nimln(543, "nativesockets.nim");
		while (1) {
			if (!(i0 < L0)) goto LA2;
			nimln(544, "nativesockets.nim");
			{
				int LOC5;
				NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_19;
				NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_20;
				if ((NU)(i0) >= (NU)((*s0)->Sup.len)) raiseIndexError();
				LOC5 = (int)0;
				LOC5 = Fdisset_NkjjeLx4p9b4GT29buKQYcxA((*s0)->data[i0], fd0);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				nimln(545, "nativesockets.nim");
				if ((NU)(i0) >= (NU)((*s0)->Sup.len)) raiseIndexError();
				T_f9bP3LqjpgpB9cXL8Nnak7tQ_19 = subInt(L0, ((NI) 1));
				if ((NU)((NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_19)) >= (NU)((*s0)->Sup.len)) raiseIndexError();
				(*s0)->data[i0] = (*s0)->data[(NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_19)];
				nimln(546, "nativesockets.nim");
				T_f9bP3LqjpgpB9cXL8Nnak7tQ_20 = subInt(L0, ((NI) 1));
				L0 = (NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_20);
			}
			goto LA3;
			LA6: ;
			{
				NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_21;
				nimln(548, "nativesockets.nim");
				T_f9bP3LqjpgpB9cXL8Nnak7tQ_21 = addInt(i0, ((NI) 1));
				i0 = (NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_21);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(549, "nativesockets.nim");
	(*s0) = (TY_qwqHTkRvwhrRyENtudHQ7g*) setLengthSeq(&((*s0))->Sup, sizeof(NI), ((NI)chckRange(L0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_NIMCALL(NI, select_eXjloAphe9a2xyF9bVEutDXA)(TY_qwqHTkRvwhrRyENtudHQ7g** readfds0, NI timeout0) {
	NI result0;
	Timeval_9boMTr1l3P8e1j9aAjdqsQtA tv0;
	Tfdset_lYo1mv6gU9aT1ZE1etM9ceog rd0;
	NI m0;
	nimfr("select", "nativesockets.nim")
	result0 = (NI)0;
	nimln(559, "nativesockets.nim");
	tv0 = timevalfrommilliseconds_8n6ccdvLo6VgMVggcNy9bzw(timeout0);
	memset((void*)(&rd0), 0, sizeof(rd0));
	nimln(562, "nativesockets.nim");
	m0 = ((NI) 0);
	nimln(563, "nativesockets.nim");
	createfdset_Uq0gtMrL5zwaOYtdZK68kg((&rd0), (*readfds0), (&m0));
	nimln(565, "nativesockets.nim");
	{
		NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_22;
		int LOC5;
		nimln(347, "system.nim");
		nimln(565, "nativesockets.nim");
		if (!!((timeout0 == ((NI) -1)))) goto LA3;
		nimln(566, "nativesockets.nim");
		T_f9bP3LqjpgpB9cXL8Nnak7tQ_22 = addInt(m0, ((NI) 1));
		LOC5 = (int)0;
		LOC5 = Dl_129473(((int)chckRange((NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_22), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd0), NIM_NIL, NIM_NIL, (&tv0));
		result0 = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_23;
		int LOC7;
		nimln(568, "nativesockets.nim");
		T_f9bP3LqjpgpB9cXL8Nnak7tQ_23 = addInt(m0, ((NI) 1));
		LOC7 = (int)0;
		LOC7 = Dl_129473(((int)chckRange((NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_23), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd0), NIM_NIL, NIM_NIL, NIM_NIL);
		result0 = ((NI) (LOC7));
	}
	LA1: ;
	nimln(570, "nativesockets.nim");
	prunesocketset_70Zyypm1k20h9c9bjjAUrOmw(readfds0, (&rd0));
	popFrame();
	return result0;
}

N_NIMCALL(NI, selectwrite_Xl49alpuj6Qo9brq9cgUHYNlQ)(TY_qwqHTkRvwhrRyENtudHQ7g** writefds0, NI timeout0) {
	NI result0;
	Timeval_9boMTr1l3P8e1j9aAjdqsQtA tv0;
	Tfdset_lYo1mv6gU9aT1ZE1etM9ceog wr0;
	NI m0;
	nimfr("selectWrite", "nativesockets.nim")
	result0 = (NI)0;
	nimln(581, "nativesockets.nim");
	tv0 = timevalfrommilliseconds_8n6ccdvLo6VgMVggcNy9bzw(timeout0);
	memset((void*)(&wr0), 0, sizeof(wr0));
	nimln(584, "nativesockets.nim");
	m0 = ((NI) 0);
	nimln(585, "nativesockets.nim");
	createfdset_Uq0gtMrL5zwaOYtdZK68kg((&wr0), (*writefds0), (&m0));
	nimln(587, "nativesockets.nim");
	{
		NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_24;
		int LOC5;
		nimln(347, "system.nim");
		nimln(587, "nativesockets.nim");
		if (!!((timeout0 == ((NI) -1)))) goto LA3;
		nimln(588, "nativesockets.nim");
		T_f9bP3LqjpgpB9cXL8Nnak7tQ_24 = addInt(m0, ((NI) 1));
		LOC5 = (int)0;
		LOC5 = Dl_129473(((int)chckRange((NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_24), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr0), NIM_NIL, (&tv0));
		result0 = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_25;
		int LOC7;
		nimln(590, "nativesockets.nim");
		T_f9bP3LqjpgpB9cXL8Nnak7tQ_25 = addInt(m0, ((NI) 1));
		LOC7 = (int)0;
		LOC7 = Dl_129473(((int)chckRange((NI)(T_f9bP3LqjpgpB9cXL8Nnak7tQ_25), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr0), NIM_NIL, NIM_NIL);
		result0 = ((NI) (LOC7));
	}
	LA1: ;
	nimln(592, "nativesockets.nim");
	prunesocketset_70Zyypm1k20h9c9bjjAUrOmw(writefds0, (&wr0));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void) {
	nimfr("nativesockets", "nativesockets.nim")
	nimln(89, "nativesockets.nim");
	osinvalidsocket_voz9aUXu8jtRbvGZZJHNE8w = INVALID_SOCKET;
	nimln(596, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(347, "system.nim");
		nimln(596, "nativesockets.nim");
		LOC3 = (int)0;
		LOC3 = Dl_129544(((NI16) 257), (&wsa_ClAT9bhT9cqG9adztamb5X9b2w));
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = (NI32)0;
		LOC6 = oslasterror_6wyvsbJUteIgEY9cC5BVJZQ();
		raiseoserror_K9a7YBjj81Bse0N0Fg7MFIA(LOC6, ((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* T_f9bP3LqjpgpB9cXL8Nnak7tQ_26[3];
NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_28;
static char* NIM_CONST T_f9bP3LqjpgpB9cXL8Nnak7tQ_27[3] = {
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* T_f9bP3LqjpgpB9cXL8Nnak7tQ_29[4];
NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_31;
static char* NIM_CONST T_f9bP3LqjpgpB9cXL8Nnak7tQ_30[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* T_f9bP3LqjpgpB9cXL8Nnak7tQ_32[6];
NI T_f9bP3LqjpgpB9cXL8Nnak7tQ_34;
static char* NIM_CONST T_f9bP3LqjpgpB9cXL8Nnak7tQ_33[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16];
NTI_Q79bEtFARvq0ekDNtvj3Vqg.size = sizeof(Domain_Q79bEtFARvq0ekDNtvj3Vqg);
NTI_Q79bEtFARvq0ekDNtvj3Vqg.kind = 14;
NTI_Q79bEtFARvq0ekDNtvj3Vqg.base = 0;
NTI_Q79bEtFARvq0ekDNtvj3Vqg.flags = 3;
for (T_f9bP3LqjpgpB9cXL8Nnak7tQ_28 = 0; T_f9bP3LqjpgpB9cXL8Nnak7tQ_28 < 3; T_f9bP3LqjpgpB9cXL8Nnak7tQ_28++) {
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_28+0].kind = 1;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_28+0].offset = T_f9bP3LqjpgpB9cXL8Nnak7tQ_28;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_28+0].name = T_f9bP3LqjpgpB9cXL8Nnak7tQ_27[T_f9bP3LqjpgpB9cXL8Nnak7tQ_28];
T_f9bP3LqjpgpB9cXL8Nnak7tQ_26[T_f9bP3LqjpgpB9cXL8Nnak7tQ_28] = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_28+0];
}
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0].offset = 0;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].offset = 2;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].offset = 23;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].len = 3; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].kind = 2; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].sons = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_26[0];
NTI_Q79bEtFARvq0ekDNtvj3Vqg.node = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3];
NTI_Q79bEtFARvq0ekDNtvj3Vqg.flags = 1<<2;
NTI_NQT1bItGG2X9byGdrWX7ujw.size = sizeof(Socktype_NQT1bItGG2X9byGdrWX7ujw);
NTI_NQT1bItGG2X9byGdrWX7ujw.kind = 14;
NTI_NQT1bItGG2X9byGdrWX7ujw.base = 0;
NTI_NQT1bItGG2X9byGdrWX7ujw.flags = 3;
for (T_f9bP3LqjpgpB9cXL8Nnak7tQ_31 = 0; T_f9bP3LqjpgpB9cXL8Nnak7tQ_31 < 4; T_f9bP3LqjpgpB9cXL8Nnak7tQ_31++) {
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_31+4].kind = 1;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_31+4].offset = T_f9bP3LqjpgpB9cXL8Nnak7tQ_31;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_31+4].name = T_f9bP3LqjpgpB9cXL8Nnak7tQ_30[T_f9bP3LqjpgpB9cXL8Nnak7tQ_31];
T_f9bP3LqjpgpB9cXL8Nnak7tQ_29[T_f9bP3LqjpgpB9cXL8Nnak7tQ_31] = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_31+4];
}
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].offset = 1;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5].offset = 2;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].offset = 3;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].offset = 5;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].len = 4; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].kind = 2; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].sons = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_29[0];
NTI_NQT1bItGG2X9byGdrWX7ujw.node = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8];
NTI_NQT1bItGG2X9byGdrWX7ujw.flags = 1<<2;
NTI_dqJ1OqRGclxIMMdSLRzzXg.size = sizeof(Protocol_dqJ1OqRGclxIMMdSLRzzXg);
NTI_dqJ1OqRGclxIMMdSLRzzXg.kind = 14;
NTI_dqJ1OqRGclxIMMdSLRzzXg.base = 0;
NTI_dqJ1OqRGclxIMMdSLRzzXg.flags = 3;
for (T_f9bP3LqjpgpB9cXL8Nnak7tQ_34 = 0; T_f9bP3LqjpgpB9cXL8Nnak7tQ_34 < 6; T_f9bP3LqjpgpB9cXL8Nnak7tQ_34++) {
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_34+9].kind = 1;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_34+9].offset = T_f9bP3LqjpgpB9cXL8Nnak7tQ_34;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_34+9].name = T_f9bP3LqjpgpB9cXL8Nnak7tQ_33[T_f9bP3LqjpgpB9cXL8Nnak7tQ_34];
T_f9bP3LqjpgpB9cXL8Nnak7tQ_32[T_f9bP3LqjpgpB9cXL8Nnak7tQ_34] = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[T_f9bP3LqjpgpB9cXL8Nnak7tQ_34+9];
}
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].offset = 6;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[10].offset = 17;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[11].offset = 18;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[12].offset = 19;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13].offset = 20;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].offset = 21;
T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].len = 6; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].kind = 2; T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].sons = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_32[0];
NTI_dqJ1OqRGclxIMMdSLRzzXg.node = &T_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15];
NTI_dqJ1OqRGclxIMMdSLRzzXg.flags = 1<<2;
if (!((T_f9bP3LqjpgpB9cXL8Nnak7tQ_2 = nimLoadLibrary((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_4))
)) nimLoadLibraryError((NimStringDesc*) &T_f9bP3LqjpgpB9cXL8Nnak7tQ_5);
	Dl_163681 = (TY_awTV7srwWeJ9cGPOCgBQa7g) nimGetProcAddr(T_f9bP3LqjpgpB9cXL8Nnak7tQ_2, "ioctlsocket");
}

