/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\MinGW\bin\gcc.exe -c  -w  -IC:\nim-0.16.0\lib -o c:\Projects\nim\HelloWorld\nimcache\stdlib_tables.o c:\Projects\nim\HelloWorld\nimcache\stdlib_tables.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Orderedtable_AF39bJ7XDr6gpANuGpxkHrw Orderedtable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct TY_MlAD6nAPq9bHKla9cWiIZP0g TY_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY_awOivLjlO76sGdHY7nQUjQ TY_awOivLjlO76sGdHY7nQUjQ;
typedef struct Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Keyerror_ifYAhUumNzWR9c9cN9amyJLtg Keyerror_ifYAhUumNzWR9c9cN9amyJLtg;
typedef struct Valueerror_Gi06FkNeykJn7mrqRZYrkA Valueerror_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TY_oLpBKXzW3hF9aCVMo5EymfQ TY_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Orderedtable_AF39bJ7XDr6gpANuGpxkHrw  {
TY_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TY_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror_Gi06FkNeykJn7mrqRZYrkA  {
  Exception Sup;
};
struct  Keyerror_ifYAhUumNzWR9c9cN9amyJLtg  {
  Valueerror_Gi06FkNeykJn7mrqRZYrkA Sup;
};
typedef NU8 Jsonnodekind_RUngo7nCHe6O8aBGIcrhtg;
struct  Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q  {
Jsonnodekind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {Orderedtable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {TY_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
struct TY_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  TY_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct TY_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode0);
static N_INLINE(NIM_BOOL, mustrehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length0, NI counter0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nexttry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h0, NI maxhash0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(NI, rightsize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count0);
N_NIMCALL(NI, nextpoweroftwo_gcitR3TEXHJ3GR9bmwIvtRA)(NI x0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
static N_NIMCALL(void, Marker_TY_MlAD6nAPq9bHKla9cWiIZP0g)(void* p, NI op);
N_NIMCALL(NIM_BOOL, ispoweroftwo_M0Db9b9cHxuUgw2ZF0P8utPg)(NI x0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
N_NIMCALL(NI, rawget_ejrpxsNAZJyHhQhopPiwJA)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0, NI* hc0);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0);
static N_INLINE(NIM_BOOL, equalmem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a0, void* b0, NI size0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(void, enlarge_eOZs9auXoZM0glvDlTLHszQ)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0);
N_NIMCALL(NI, rawgetknownhc_DycNfqFZryzkgIAk9bw7xSQ)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0, NI hc0);
N_NIMCALL(void, rawinsert_PJEZeDCLfp6559cI0Hhn8lg)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, TY_MlAD6nAPq9bHKla9cWiIZP0g** data0, NimStringDesc* key0, Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q* val0, NI hc0, NI h0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(NI, rawget_WyEeYQHki9bxcrycmQ047tQtables)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0, NI* hc0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_AF39bJ7XDr6gpANuGpxkHrw;
TNimType NTI_awOivLjlO76sGdHY7nQUjQ;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg;
extern TNimType NTI_zfzzuQ8txrdZAYK0WGWpHg;
TNimType NTI_MlAD6nAPq9bHKla9cWiIZP0g;
extern Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_axqhRnwd09cVJkRcojfw6mA;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg;
STRING_LITERAL(T_4SoG2KRQy3oMm9aUzSLtGrA_2, "\015\012  counter < length ", 21);
STRING_LITERAL(T_4SoG2KRQy3oMm9aUzSLtGrA_12, "isPowerOfTwo(initialSize) ", 26);
STRING_LITERAL(T_4SoG2KRQy3oMm9aUzSLtGrA_20, "key not found: ", 15);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isempty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isEmpty", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(15, "tableimpl.nim");
	result0 = (hcode0 == ((NI) 0));
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isFilled", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(18, "tableimpl.nim");
	nimln(347, "system.nim");
	nimln(18, "tableimpl.nim");
	result0 = !((hcode0 == ((NI) 0)));
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NIM_BOOL, mustrehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length0, NI counter0) {
	NIM_BOOL result0;
	NIM_BOOL LOC5;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_3;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_4;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_5;
	nimfr("mustRehash", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(24, "tableimpl.nim");
	{
		if (!!((counter0 < length0))) goto LA3;
		failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_4SoG2KRQy3oMm9aUzSLtGrA_2));
	}
	LA3: ;
	nimln(25, "tableimpl.nim");
	LOC5 = (NIM_BOOL)0;
	T_4SoG2KRQy3oMm9aUzSLtGrA_3 = mulInt(length0, ((NI) 2));
	T_4SoG2KRQy3oMm9aUzSLtGrA_4 = mulInt(counter0, ((NI) 3));
	LOC5 = ((NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_3) < (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_4));
	if (LOC5) goto LA6;
	T_4SoG2KRQy3oMm9aUzSLtGrA_5 = subInt(length0, counter0);
	LOC5 = ((NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_5) < ((NI) 4));
	LA6: ;
	result0 = LOC5;
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, nexttry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h0, NI maxhash0) {
	NI result0;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_6;
	nimfr("nextTry", "tableimpl.nim")
	result0 = (NI)0;
	nimln(28, "tableimpl.nim");
	T_4SoG2KRQy3oMm9aUzSLtGrA_6 = addInt(h0, ((NI) 1));
	result0 = (NI)((NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_6) & maxhash0);
	popFrame();
	return result0;
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, rightsize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count0) {
	NI result0;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_7;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_8;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_9;
	nimfr("rightSize", "tables.nim")
	result0 = (NI)0;
	nimln(136, "tables.nim");
	T_4SoG2KRQy3oMm9aUzSLtGrA_7 = mulInt(((NI) (count0)), ((NI) 3));
	T_4SoG2KRQy3oMm9aUzSLtGrA_8 = divInt(((NI) ((NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_7))), ((NI) 2));
	T_4SoG2KRQy3oMm9aUzSLtGrA_9 = addInt(((NI) ((NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_8))), ((NI) 4));
	result0 = nextpoweroftwo_gcitR3TEXHJ3GR9bmwIvtRA(((NI) ((NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_9))));
	popFrame();
	return result0;
}
static N_NIMCALL(void, Marker_TY_MlAD6nAPq9bHKla9cWiIZP0g)(void* p, NI op) {
	TY_MlAD6nAPq9bHKla9cWiIZP0g* a;
	NI LOC1;
	a = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	nimGCvisit((void*)a->data[LOC1].Field3, op);
	}
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, initorderedtable_PHRF9cHqhXGiWC9cIiRW9bTWw)(NI initialsize0, Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* Result) {
	nimfr("initOrderedTable", "tables.nim")
	nimln(602, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = ispoweroftwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialsize0);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_4SoG2KRQy3oMm9aUzSLtGrA_12));
	}
	LA4: ;
	nimln(603, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(604, "tables.nim");
	(*Result).first = ((NI) -1);
	nimln(605, "tables.nim");
	(*Result).last = ((NI) -1);
	nimln(606, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (TY_MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTI_MlAD6nAPq9bHKla9cWiIZP0g), ((NI)chckRange(initialsize0, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

static N_INLINE(NIM_BOOL, equalmem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a0, void* b0, NI size0) {
	NIM_BOOL result0;
	int LOC1;
	result0 = (NIM_BOOL)0;
	LOC1 = (int)0;
	LOC1 = memcmp(a0, b0, ((size_t) (size0)));
	result0 = (LOC1 == ((NI32) 0));
	return result0;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0) {
	NIM_BOOL result0;
	NIM_BOOL LOC11;
{	result0 = (NIM_BOOL)0;
	{
		if (!(a0 == b0)) goto LA3;
		result0 = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b0 == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = (NIM_BOOL)0;
	LOC11 = ((*a0).Sup.len == (*b0).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC11 = equalmem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a0).data)), ((void*) ((*b0).data)), ((NI) ((*a0).Sup.len)));
	LA12: ;
	result0 = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, rawget_ejrpxsNAZJyHhQhopPiwJA)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0, NI* hc0) {
	NI result0;
	NI h0;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_13;
	nimfr("rawGet", "tables.nim")
{	result0 = (NI)0;
	nimln(43, "tableimpl.nim");
	(*hc0) = hash_uBstFm5SYVQeOL3j9c9bc58A(key0);
	nimln(53, "tableimpl.nim");
	{
		if (!((*hc0) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc0) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)((*hc0) & ((*t0).data ? ((*t0).data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
			LOC7 = (NIM_BOOL)0;
			LOC7 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t0).data->data[h0].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
				LOC10 = ((*t0).data->data[h0].Field0 == (*hc0));
				if (!(LOC10)) goto LA11;
				if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings((*t0).data->data[h0].Field2, key0);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, ((*t0).data ? ((*t0).data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(524, "tables.nim");
	nimln(40, "tableimpl.nim");
	T_4SoG2KRQy3oMm9aUzSLtGrA_13 = subInt(((NI) -1), h0);
	result0 = (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_13);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(280, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(280, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(281, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		nimln(282, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(283, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(283, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(284, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		nimln(285, "gc.nim");
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(286, "gc.nim");
			rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(287, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(NI, rawgetknownhc_DycNfqFZryzkgIAk9bw7xSQ)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0, NI hc0) {
	NI result0;
	NI h0;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_15;
	nimfr("rawGetKnownHC", "tables.nim")
{	result0 = (NI)0;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)(hc0 & ((*t0).data ? ((*t0).data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
			LOC3 = (NIM_BOOL)0;
			LOC3 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t0).data->data[h0].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
				LOC6 = ((*t0).data->data[h0].Field0 == hc0);
				if (!(LOC6)) goto LA7;
				if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings((*t0).data->data[h0].Field2, key0);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, ((*t0).data ? ((*t0).data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(518, "tables.nim");
	nimln(40, "tableimpl.nim");
	T_4SoG2KRQy3oMm9aUzSLtGrA_15 = subInt(((NI) -1), h0);
	result0 = (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_15);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(262, "gc.nim");
	c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p0);
	nimln(264, "gc.nim");
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(265, "gc.nim");
		rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_PJEZeDCLfp6559cI0Hhn8lg)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, TY_MlAD6nAPq9bHKla9cWiIZP0g** data0, NimStringDesc* key0, Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q* val0, NI hc0, NI h0) {
	NimStringDesc* LOC1;
	nimfr("rawInsert", "tables.nim")
	nimln(64, "tableimpl.nim");
	if ((NU)(h0) >= (NU)((*data0)->Sup.len)) raiseIndexError();
	LOC1 = (NimStringDesc*)0;
	LOC1 = (*data0)->data[h0].Field2; (*data0)->data[h0].Field2 = copyStringRC1(key0);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(65, "tableimpl.nim");
	if ((NU)(h0) >= (NU)((*data0)->Sup.len)) raiseIndexError();
	asgnRefNoCycle((void**) (&(*data0)->data[h0].Field3), val0);
	nimln(559, "tables.nim");
	if ((NU)(h0) >= (NU)((*data0)->Sup.len)) raiseIndexError();
	(*data0)->data[h0].Field0 = hc0;
	nimln(560, "tables.nim");
	if ((NU)(h0) >= (NU)((*data0)->Sup.len)) raiseIndexError();
	(*data0)->data[h0].Field1 = ((NI) -1);
	nimln(561, "tables.nim");
	{
		if (!((*t0).first < ((NI) 0))) goto LA4;
		(*t0).first = h0;
	}
	LA4: ;
	nimln(562, "tables.nim");
	{
		if (!(((NI) 0) <= (*t0).last)) goto LA8;
		if ((NU)((*t0).last) >= (NU)((*data0)->Sup.len)) raiseIndexError();
		(*data0)->data[(*t0).last].Field1 = h0;
	}
	LA8: ;
	nimln(563, "tables.nim");
	(*t0).last = h0;
	popFrame();
}

N_NIMCALL(void, enlarge_eOZs9auXoZM0glvDlTLHszQ)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0) {
	TY_MlAD6nAPq9bHKla9cWiIZP0g* n0;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_14;
	NI h0;
	TY_MlAD6nAPq9bHKla9cWiIZP0g* LOC1;
	nimfr("enlarge", "tables.nim")
	n0 = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)0;
	nimln(567, "tables.nim");
	T_4SoG2KRQy3oMm9aUzSLtGrA_14 = mulInt(((*t0).data ? (*t0).data->Sup.len : 0), ((NI) 2));
	n0 = (TY_MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTI_MlAD6nAPq9bHKla9cWiIZP0g), ((NI)chckRange((NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_14), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(568, "tables.nim");
	h0 = (*t0).first;
	nimln(569, "tables.nim");
	(*t0).first = ((NI) -1);
	nimln(570, "tables.nim");
	(*t0).last = ((NI) -1);
	nimln(571, "tables.nim");
	LOC1 = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)0;
	LOC1 = (*t0).data;
	unsureAsgnRef((void**) (&(*t0).data), n0);
	n0 = LOC1;
	{
		nimln(572, "tables.nim");
		while (1) {
			NI nxt0;
			if (!(((NI) 0) <= h0)) goto LA3;
			nimln(573, "tables.nim");
			if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
			nxt0 = n0->data[h0].Field1;
			nimln(574, "tables.nim");
			{
				NIM_BOOL LOC6;
				NI j0;
				NI LOC9;
				NI T_4SoG2KRQy3oMm9aUzSLtGrA_16;
				if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
				LOC6 = (NIM_BOOL)0;
				LOC6 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(n0->data[h0].Field0);
				if (!LOC6) goto LA7;
				nimln(575, "tables.nim");
				if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
				if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
				LOC9 = (NI)0;
				LOC9 = rawgetknownhc_DycNfqFZryzkgIAk9bw7xSQ((&(*t0)), n0->data[h0].Field2, n0->data[h0].Field0);
				T_4SoG2KRQy3oMm9aUzSLtGrA_16 = subInt(((NI) -1), LOC9);
				j0 = (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_16);
				nimln(576, "tables.nim");
				if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
				if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
				if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
				rawinsert_PJEZeDCLfp6559cI0Hhn8lg(t0, (&(*t0).data), n0->data[h0].Field2, n0->data[h0].Field3, n0->data[h0].Field0, j0);
			}
			LA7: ;
			nimln(577, "tables.nim");
			h0 = nxt0;
		} LA3: ;
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_9bwm9c9bGAcoIGLjRndWCPT3Q)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0, Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q* val0) {
	NI hc0;
	NI index0;
	nimfr("[]=", "tables.nim")
	hc0 = (NI)0;
	nimln(98, "tableimpl.nim");
	index0 = rawget_ejrpxsNAZJyHhQhopPiwJA((&(*t0)), key0, (&hc0));
	nimln(581, "tables.nim");
	{
		nimln(99, "tableimpl.nim");
		if (!(((NI) 0) <= index0)) goto LA3;
		if ((NU)(index0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
		asgnRefNoCycle((void**) (&(*t0).data->data[index0].Field3), val0);
	}
	goto LA1;
	LA3: ;
	{
		NI T_4SoG2KRQy3oMm9aUzSLtGrA_17;
		NI T_4SoG2KRQy3oMm9aUzSLtGrA_18;
		nimln(89, "tableimpl.nim");
		{
			NIM_BOOL LOC8;
			nimln(117, "tables.nim");
			LOC8 = (NIM_BOOL)0;
			LOC8 = mustrehash_CT8KHtrz1uoHrT4RgfOSmQtables(((*t0).data ? (*t0).data->Sup.len : 0), (*t0).counter);
			if (!LOC8) goto LA9;
			nimln(90, "tableimpl.nim");
			enlarge_eOZs9auXoZM0glvDlTLHszQ(t0);
			nimln(91, "tableimpl.nim");
			index0 = rawgetknownhc_DycNfqFZryzkgIAk9bw7xSQ((&(*t0)), key0, hc0);
		}
		LA9: ;
		nimln(92, "tableimpl.nim");
		T_4SoG2KRQy3oMm9aUzSLtGrA_17 = subInt(((NI) -1), index0);
		index0 = (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_17);
		nimln(93, "tableimpl.nim");
		rawinsert_PJEZeDCLfp6559cI0Hhn8lg(t0, (&(*t0).data), key0, val0, hc0, index0);
		nimln(94, "tableimpl.nim");
		T_4SoG2KRQy3oMm9aUzSLtGrA_18 = addInt((*t0).counter, ((NI) 1));
		(*t0).counter = (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_18);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, haskey_6zZzy9aTG3euSh9bJ9bh9aFOqA)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0) {
	NIM_BOOL result0;
	NI hc0;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result0 = (NIM_BOOL)0;
	hc0 = (NI)0;
	nimln(550, "tables.nim");
	LOC1 = (NI)0;
	LOC1 = rawget_ejrpxsNAZJyHhQhopPiwJA(t0, key0, (&hc0));
	result0 = (((NI) 0) <= LOC1);
	popFrame();
	return result0;
}

static N_INLINE(NI, rawget_WyEeYQHki9bxcrycmQ047tQtables)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0, NI* hc0) {
	NI result0;
	NI h0;
	NI T_4SoG2KRQy3oMm9aUzSLtGrA_19;
	nimfr("rawGet", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(43, "tableimpl.nim");
	(*hc0) = hash_uBstFm5SYVQeOL3j9c9bc58A(key0);
	nimln(53, "tableimpl.nim");
	{
		if (!((*hc0) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc0) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)((*hc0) & ((*t0).data ? ((*t0).data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
			LOC7 = (NIM_BOOL)0;
			LOC7 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t0).data->data[h0].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
				LOC10 = ((*t0).data->data[h0].Field0 == (*hc0));
				if (!(LOC10)) goto LA11;
				if ((NU)(h0) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings((*t0).data->data[h0].Field2, key0);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, ((*t0).data ? ((*t0).data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(75, "tableimpl.nim");
	nimln(40, "tableimpl.nim");
	T_4SoG2KRQy3oMm9aUzSLtGrA_19 = subInt(((NI) -1), h0);
	result0 = (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_19);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_NIMCALL(Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q**, HEX5BHEX5D_9bcSZUFhwESDEYXhkxOm8Hg)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0) {
	Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q** result0;
	NI hc_u3sucX4OC9aCI319cyzPfnPQ;
	NI index_Nls85AySj3R9b5dTKo8K8zA;
	nimfr("[]", "tables.nim")
	result0 = (Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q**)0;
	hc_u3sucX4OC9aCI319cyzPfnPQ = (NI)0;
	nimln(147, "tables.nim");
	index_Nls85AySj3R9b5dTKo8K8zA = rawget_WyEeYQHki9bxcrycmQ047tQtables((&(*t0)), key0, (&hc_u3sucX4OC9aCI319cyzPfnPQ));
	nimln(535, "tables.nim");
	{
		nimln(148, "tables.nim");
		if (!(((NI) 0) <= index_Nls85AySj3R9b5dTKo8K8zA)) goto LA3;
		if ((NU)(index_Nls85AySj3R9b5dTKo8K8zA) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
		result0 = &(*t0).data->data[index_Nls85AySj3R9b5dTKo8K8zA].Field3;
	}
	goto LA1;
	LA3: ;
	{
		Keyerror_ifYAhUumNzWR9c9cN9amyJLtg* e_3KTaTU0PkrRBJE9cyBTzsPA;
		NimStringDesc* LOC6;
		e_3KTaTU0PkrRBJE9cyBTzsPA = (Keyerror_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln(2560, "system.nim");
		e_3KTaTU0PkrRBJE9cyBTzsPA = (Keyerror_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA), sizeof(Keyerror_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e_3KTaTU0PkrRBJE9cyBTzsPA).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg);
		nimln(2561, "system.nim");
		nimln(151, "tables.nim");
		LOC6 = (NimStringDesc*)0;
		nimln(535, "tables.nim");
		LOC6 = rawNewString(key0->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &T_4SoG2KRQy3oMm9aUzSLtGrA_20));
appendString(LOC6, key0);
		asgnRefNoCycle((void**) (&(*e_3KTaTU0PkrRBJE9cyBTzsPA).Sup.Sup.message), LOC6);
		nimln(151, "tables.nim");
		raiseException((Exception*)e_3KTaTU0PkrRBJE9cyBTzsPA, "KeyError");
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q*, getordefault_eiC0QjqFEL1eMy9c1lEf0RA)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0) {
	Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q* result0;
	NI hc_ahatuxPT9c9c9blViOJsJlR0g;
	NI index_lVyLcP9bhOrALHBukLVhV9aQ;
	nimfr("getOrDefault", "tables.nim")
	result0 = (Jsonnodeobj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	hc_ahatuxPT9c9c9blViOJsJlR0g = (NI)0;
	nimln(158, "tables.nim");
	index_lVyLcP9bhOrALHBukLVhV9aQ = rawget_WyEeYQHki9bxcrycmQ047tQtables(t0, key0, (&hc_ahatuxPT9c9c9blViOJsJlR0g));
	nimln(544, "tables.nim");
	{
		nimln(159, "tables.nim");
		if (!(((NI) 0) <= index_lVyLcP9bhOrALHBukLVhV9aQ)) goto LA3;
		if ((NU)(index_lVyLcP9bhOrALHBukLVhV9aQ) >= (NU)((*t0).data->Sup.len)) raiseIndexError();
		result0 = (*t0).data->data[index_lVyLcP9bhOrALHBukLVhV9aQ].Field3;
	}
	LA3: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, del_kBvF4V6kGI5xT2NUPtOV5g)(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw* t0, NimStringDesc* key0) {
	TY_MlAD6nAPq9bHKla9cWiIZP0g* n0;
	NI h0;
	TY_MlAD6nAPq9bHKla9cWiIZP0g* LOC1;
	NI hc0;
	NI res_W4fNA1DE1Ix3hll6O7GOTw;
	nimfr("del", "tables.nim")
	n0 = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)0;
	nimln(782, "tables.nim");
	n0 = (TY_MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTI_MlAD6nAPq9bHKla9cWiIZP0g), ((NI)chckRange(((*t0).data ? (*t0).data->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(783, "tables.nim");
	h0 = (*t0).first;
	nimln(784, "tables.nim");
	(*t0).first = ((NI) -1);
	nimln(785, "tables.nim");
	(*t0).last = ((NI) -1);
	nimln(786, "tables.nim");
	LOC1 = (TY_MlAD6nAPq9bHKla9cWiIZP0g*)0;
	LOC1 = (*t0).data;
	unsureAsgnRef((void**) (&(*t0).data), n0);
	n0 = LOC1;
	nimln(787, "tables.nim");
	res_W4fNA1DE1Ix3hll6O7GOTw = (NI)0;
	nimln(43, "tableimpl.nim");
	res_W4fNA1DE1Ix3hll6O7GOTw = hash_uBstFm5SYVQeOL3j9c9bc58A(key0);
	nimln(49, "tableimpl.nim");
	{
		if (!(res_W4fNA1DE1Ix3hll6O7GOTw == ((NI) 0))) goto LA4;
		nimln(45, "tableimpl.nim");
		res_W4fNA1DE1Ix3hll6O7GOTw = ((NI) 314159265);
	}
	LA4: ;
	hc0 = res_W4fNA1DE1Ix3hll6O7GOTw;
	{
		nimln(788, "tables.nim");
		while (1) {
			NI nxt0;
			if (!(((NI) 0) <= h0)) goto LA7;
			nimln(789, "tables.nim");
			if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
			nxt0 = n0->data[h0].Field1;
			nimln(790, "tables.nim");
			{
				NIM_BOOL LOC10;
				if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
				LOC10 = (NIM_BOOL)0;
				LOC10 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(n0->data[h0].Field0);
				if (!LOC10) goto LA11;
				nimln(791, "tables.nim");
				{
					NIM_BOOL LOC15;
					NI T_4SoG2KRQy3oMm9aUzSLtGrA_21;
					LOC15 = (NIM_BOOL)0;
					if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
					LOC15 = (n0->data[h0].Field0 == hc0);
					if (!(LOC15)) goto LA16;
					if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
					LOC15 = eqStrings(n0->data[h0].Field2, key0);
					LA16: ;
					if (!LOC15) goto LA17;
					nimln(792, "tables.nim");
					T_4SoG2KRQy3oMm9aUzSLtGrA_21 = subInt((*t0).counter, ((NI) 1));
					(*t0).counter = (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_21);
				}
				goto LA13;
				LA17: ;
				{
					NI j0;
					NI LOC20;
					NI T_4SoG2KRQy3oMm9aUzSLtGrA_22;
					nimln(794, "tables.nim");
					if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
					if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
					LOC20 = (NI)0;
					LOC20 = rawgetknownhc_DycNfqFZryzkgIAk9bw7xSQ((&(*t0)), n0->data[h0].Field2, n0->data[h0].Field0);
					T_4SoG2KRQy3oMm9aUzSLtGrA_22 = subInt(((NI) -1), LOC20);
					j0 = (NI)(T_4SoG2KRQy3oMm9aUzSLtGrA_22);
					nimln(795, "tables.nim");
					if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
					if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
					if ((NU)(h0) >= (NU)(n0->Sup.len)) raiseIndexError();
					rawinsert_PJEZeDCLfp6559cI0Hhn8lg(t0, (&(*t0).data), n0->data[h0].Field2, n0->data[h0].Field3, n0->data[h0].Field0, j0);
				}
				LA13: ;
			}
			LA11: ;
			nimln(796, "tables.nim");
			h0 = nxt0;
		} LA7: ;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* T_4SoG2KRQy3oMm9aUzSLtGrA_10[4];
static TNimNode* T_4SoG2KRQy3oMm9aUzSLtGrA_11[4];
static TNimNode T_4SoG2KRQy3oMm9aUzSLtGrA_0[10];
NTI_AF39bJ7XDr6gpANuGpxkHrw.size = sizeof(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw);
NTI_AF39bJ7XDr6gpANuGpxkHrw.kind = 18;
NTI_AF39bJ7XDr6gpANuGpxkHrw.base = 0;
NTI_AF39bJ7XDr6gpANuGpxkHrw.flags = 2;
T_4SoG2KRQy3oMm9aUzSLtGrA_10[0] = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[1];
NTI_awOivLjlO76sGdHY7nQUjQ.size = sizeof(TY_awOivLjlO76sGdHY7nQUjQ);
NTI_awOivLjlO76sGdHY7nQUjQ.kind = 18;
NTI_awOivLjlO76sGdHY7nQUjQ.base = 0;
NTI_awOivLjlO76sGdHY7nQUjQ.flags = 2;
T_4SoG2KRQy3oMm9aUzSLtGrA_11[0] = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[3];
T_4SoG2KRQy3oMm9aUzSLtGrA_0[3].kind = 1;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[3].offset = offsetof(TY_awOivLjlO76sGdHY7nQUjQ, Field0);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[3].name = "Field0";
T_4SoG2KRQy3oMm9aUzSLtGrA_11[1] = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[4];
T_4SoG2KRQy3oMm9aUzSLtGrA_0[4].kind = 1;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[4].offset = offsetof(TY_awOivLjlO76sGdHY7nQUjQ, Field1);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[4].name = "Field1";
T_4SoG2KRQy3oMm9aUzSLtGrA_11[2] = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[5];
T_4SoG2KRQy3oMm9aUzSLtGrA_0[5].kind = 1;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[5].offset = offsetof(TY_awOivLjlO76sGdHY7nQUjQ, Field2);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[5].name = "Field2";
T_4SoG2KRQy3oMm9aUzSLtGrA_11[3] = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[6];
T_4SoG2KRQy3oMm9aUzSLtGrA_0[6].kind = 1;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[6].offset = offsetof(TY_awOivLjlO76sGdHY7nQUjQ, Field3);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[6].typ = (&NTI_zfzzuQ8txrdZAYK0WGWpHg);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[6].name = "Field3";
T_4SoG2KRQy3oMm9aUzSLtGrA_0[2].len = 4; T_4SoG2KRQy3oMm9aUzSLtGrA_0[2].kind = 2; T_4SoG2KRQy3oMm9aUzSLtGrA_0[2].sons = &T_4SoG2KRQy3oMm9aUzSLtGrA_11[0];
NTI_awOivLjlO76sGdHY7nQUjQ.node = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[2];
NTI_MlAD6nAPq9bHKla9cWiIZP0g.size = sizeof(TY_MlAD6nAPq9bHKla9cWiIZP0g*);
NTI_MlAD6nAPq9bHKla9cWiIZP0g.kind = 24;
NTI_MlAD6nAPq9bHKla9cWiIZP0g.base = (&NTI_awOivLjlO76sGdHY7nQUjQ);
NTI_MlAD6nAPq9bHKla9cWiIZP0g.flags = 2;
NTI_MlAD6nAPq9bHKla9cWiIZP0g.marker = Marker_TY_MlAD6nAPq9bHKla9cWiIZP0g;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[1].kind = 1;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[1].offset = offsetof(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw, data);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[1].typ = (&NTI_MlAD6nAPq9bHKla9cWiIZP0g);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[1].name = "data";
T_4SoG2KRQy3oMm9aUzSLtGrA_10[1] = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[7];
T_4SoG2KRQy3oMm9aUzSLtGrA_0[7].kind = 1;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[7].offset = offsetof(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw, counter);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[7].name = "counter";
T_4SoG2KRQy3oMm9aUzSLtGrA_10[2] = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[8];
T_4SoG2KRQy3oMm9aUzSLtGrA_0[8].kind = 1;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[8].offset = offsetof(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw, first);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[8].name = "first";
T_4SoG2KRQy3oMm9aUzSLtGrA_10[3] = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[9];
T_4SoG2KRQy3oMm9aUzSLtGrA_0[9].kind = 1;
T_4SoG2KRQy3oMm9aUzSLtGrA_0[9].offset = offsetof(Orderedtable_AF39bJ7XDr6gpANuGpxkHrw, last);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[9].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_4SoG2KRQy3oMm9aUzSLtGrA_0[9].name = "last";
T_4SoG2KRQy3oMm9aUzSLtGrA_0[0].len = 4; T_4SoG2KRQy3oMm9aUzSLtGrA_0[0].kind = 2; T_4SoG2KRQy3oMm9aUzSLtGrA_0[0].sons = &T_4SoG2KRQy3oMm9aUzSLtGrA_10[0];
NTI_AF39bJ7XDr6gpANuGpxkHrw.node = &T_4SoG2KRQy3oMm9aUzSLtGrA_0[0];
}

