/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\MinGW\bin\gcc.exe -c  -w  -IC:\nim-0.16.0\lib -o c:\Projects\nim\HelloWorld\nimcache\stdlib_httpcore.o c:\Projects\nim\HelloWorld\nimcache\stdlib_httpcore.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
typedef struct Table_LLQadDAXEvd71UDdEc3lDA Table_LLQadDAXEvd71UDdEc3lDA;
typedef struct TY_wOvXi5VibnCNgN9buQRQD4A TY_wOvXi5VibnCNgN9buQRQD4A;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY_sM4lkSb7zS6F7OVMvW9cffQ TY_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TY_JiteSJxrvz63iP2o9bcn2Sg TY_JiteSJxrvz63iP2o9bcn2Sg;
typedef struct TY_g1w83cyyBYiVU9c8WEJWnjQ TY_g1w83cyyBYiVU9c8WEJWnjQ;
typedef struct HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TY_UV3llMMYFckfui8YMBuUZA TY_UV3llMMYFckfui8YMBuUZA;
typedef struct TY_29caZmiPrO6d9cg0Ucdm9bdAA TY_29caZmiPrO6d9cg0Ucdm9bdAA;
typedef struct TY_kN8up2W6YKc5YA9avn5mV5w TY_kN8up2W6YKc5YA9avn5mV5w;
typedef struct Slice_qL3WGViqT0p5sVr4YFHsLg Slice_qL3WGViqT0p5sVr4YFHsLg;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Table_LLQadDAXEvd71UDdEc3lDA  {
TY_JiteSJxrvz63iP2o9bcn2Sg* data;
NI counter;
};
struct TY_g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringDesc* Field1;
TY_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
};
struct  HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA  {
Table_LLQadDAXEvd71UDdEc3lDA* table;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
};
struct TY_wOvXi5VibnCNgN9buQRQD4A {
NimStringDesc* Field0;
TY_sM4lkSb7zS6F7OVMvW9cffQ* Field1;
};
struct TY_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NimStringDesc* TY_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 TY_nmiMWKVIe46vacnhAFrQvw_Set[32];
typedef NU8 Httpversion_QPubEzrnvJXtiz9alIdNQeA;
struct TY_kN8up2W6YKc5YA9avn5mV5w {
NimStringDesc* Field0;
NI Field1;
NI Field2;
};
typedef NU16 Httpmethod_wfZHspwVKQPl9aWhkIcMrAA_Set;
typedef NU8 Httpmethod_wfZHspwVKQPl9aWhkIcMrAA;
struct  Slice_qL3WGViqT0p5sVr4YFHsLg  {
NI a;
NI b;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
struct TY_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY_29caZmiPrO6d9cg0Ucdm9bdAA {
  TGenericSeq Sup;
  TY_wOvXi5VibnCNgN9buQRQD4A data[SEQ_DECL_SIZE];
};
struct TY_JiteSJxrvz63iP2o9bcn2Sg {
  TGenericSeq Sup;
  TY_g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(Table_LLQadDAXEvd71UDdEc3lDA*, newtable_vwPfOZ6WCX1qHilQ0EWk9bQ)(TY_wOvXi5VibnCNgN9buQRQD4A* pairs0, NI pairs0Len0);
N_NIMCALL(void, totable_KvTZkBNepHskThOGwbKNQw)(TY_wOvXi5VibnCNgN9buQRQD4A* pairs0, NI pairs0Len0, Table_LLQadDAXEvd71UDdEc3lDA* Result);
N_NIMCALL(void, inittable_11SA0A9aqibwRCaMRv3dYJg)(NI initialsize0, Table_LLQadDAXEvd71UDdEc3lDA* Result);
N_NIMCALL(void, HEX5BHEX5DHEX3D_un8Mk4BNkyXrzCk9aVyJLyg)(Table_LLQadDAXEvd71UDdEc3lDA* t0, NimStringDesc* key0, TY_sM4lkSb7zS6F7OVMvW9cffQ* val0);
static N_INLINE(NI, rawget_IKEP9cnFCFaJ7ddTfNBNwiAtables)(Table_LLQadDAXEvd71UDdEc3lDA t0, NimStringDesc* key0, NI* hc0);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x0);
static N_INLINE(NIM_BOOL, isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0);
static N_INLINE(NIM_BOOL, equalmem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a0, void* b0, NI size0);
static N_INLINE(NI, nexttry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h0, NI maxhash0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(void, enlarge_4fNF0muhv9bnh9cyCNXdBTGw)(Table_LLQadDAXEvd71UDdEc3lDA* t0);
N_NIMCALL(void, rawinsert_b307VXuGrKMvRrWyJu8KAA)(Table_LLQadDAXEvd71UDdEc3lDA* t0, TY_JiteSJxrvz63iP2o9bcn2Sg** data0, NimStringDesc* key0, TY_sM4lkSb7zS6F7OVMvW9cffQ* val0, NI hc0, NI h0);
static N_INLINE(NI, rawgetknownhc_RKwyKXZlTvFd0VZfVx9bcgQtables)(Table_LLQadDAXEvd71UDdEc3lDA t0, NimStringDesc* key0, NI hc0);
N_NIMCALL(Table_LLQadDAXEvd71UDdEc3lDA*, newtable_CI6CAcgU9cmDZWyfVHj8z4g)(NI initialsize0);
N_NIMCALL(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*, newhttpheaders_6szM8dtom9bIqki4DkcPGmg)(void);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
static N_NIMCALL(void, Marker_TY_FbZeO4trJhT2CCJ9aLxejqw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*, newhttpheaders_2cpWqwa9aUbsdj1oKqpSfow)(TY_UV3llMMYFckfui8YMBuUZA* keyvaluepairs0, NI keyvaluepairs0Len0);
static N_NIMCALL(void, Marker_TY_29caZmiPrO6d9cg0Ucdm9bdAA)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq0, NI elemsize0);
N_NIMCALL(void, genericSeqAssign)(void* dest0, void* src_qi9cfsBnd42r9a9cpCLO10jow, TNimType* mt0);
N_NIMCALL(void, clear_axjU83goYo2deNG5N5zCTA)(Table_LLQadDAXEvd71UDdEc3lDA* t0);
N_NIMCALL(void, clear_OorRT6sittWQ6hHggIcv7A)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ**, HEX5BHEX5D_Q3d9cok5U8i0JCsF7VnnIJw)(Table_LLQadDAXEvd71UDdEc3lDA* t0, NimStringDesc* key0);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ**, HEX5BHEX5D_IuN3JD9aQgZX7ND9cYyXSo8g)(Table_LLQadDAXEvd71UDdEc3lDA* t0, NimStringDesc* key0);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, HEX5BHEX5D_2I7W00Lgs3jqrdJTli4b9cA)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0);
N_NIMCALL(NimStringDesc*, tostring_lBEoN6A9bKNublZsSxuhYeA)(TY_sM4lkSb7zS6F7OVMvW9cffQ* values0);
N_NIMCALL(NimStringDesc*, HEX5BHEX5D_vxOYVkVCdrAoGHSvYOjvYA)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, NI i0);
N_NIMCALL(void, HEX5BHEX5DHEX3D_Hk6a82dIBZqReb79aiZ9czeQ)(Table_LLQadDAXEvd71UDdEc3lDA* t0, NimStringDesc* key0, TY_sM4lkSb7zS6F7OVMvW9cffQ* val0);
N_NIMCALL(void, HEX5BHEX5DHEX3D_WBU77bh0wmagRXPlwfoQ4w)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, NimStringDesc* value0);
N_NIMCALL(void, HEX5BHEX5DHEX3D_TqzBU8hdRGHa9aQu0RrPqCw)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, TY_sM4lkSb7zS6F7OVMvW9cffQ* value0);
N_NIMCALL(NIM_BOOL, haskey_dVPEHWNM9ac65s5ksvHbOhg)(Table_LLQadDAXEvd71UDdEc3lDA* t0, NimStringDesc* key0);
N_NIMCALL(NIM_BOOL, haskey_pcmEVCyAwAm4n6uMb9bd7mQ)(Table_LLQadDAXEvd71UDdEc3lDA t0, NimStringDesc* key0);
N_NIMCALL(void, add_WBU77bh0wmagRXPlwfoQ4w_2)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, NimStringDesc* value0);
N_NIMCALL(void, del_xE9c9cVqHJHvzjbqM89cWGX2w)(Table_LLQadDAXEvd71UDdEc3lDA* t0, NimStringDesc* key0);
N_NIMCALL(void, del_qvMk5umInCk9bpiZXt9aZZvg)(Table_LLQadDAXEvd71UDdEc3lDA* t0, NimStringDesc* key0);
N_NIMCALL(void, del_9ctXA59cPMtAzCsUvbEbVV9bg)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0);
N_NIMCALL(NIM_BOOL, contains_oFJPRbcAHZLz4RVXeZruJw)(TY_sM4lkSb7zS6F7OVMvW9cffQ* values0, NimStringDesc* value0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
N_NIMCALL(NIM_BOOL, haskey_T0KkqFbqlm8065Ws4h4NSg)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0);
N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, getordefault_iYU3axHYDC9bL2abC1Ss5fw)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, TY_sM4lkSb7zS6F7OVMvW9cffQ* default_PmXnNu6StMyVAa1WAcbs9aA);
N_NIMCALL(NI, len_gPutmFMjF2dpNdfOqcokuQ)(Table_LLQadDAXEvd71UDdEc3lDA* t0);
N_NIMCALL(NI, len_KJLsaxEBMwC7Zow21T6yQA)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0);
N_NIMCALL(NI, parselist_ezobL19b9cekPtKoupwBaGvA)(NimStringDesc* line0, TY_sM4lkSb7zS6F7OVMvW9cffQ** list0, NI start0);
static N_INLINE(NI, skipwhitespace_eRDxv9ah1K9c5mDt1GmbdF9aghttpcore)(NimStringDesc* s0, NI start0);
static N_INLINE(NI, parseuntil_zSglkPmqQkVaLkVSiDuiCguri)(NimStringDesc* s0, NimStringDesc** token0, TY_nmiMWKVIe46vacnhAFrQvw_Set until0, NI start0);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s0, NI start_WPWyPKk58Cr5a6XFFviMjg, NI last0);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s0, NI first0, NI last0);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s0, NI newlen0);
N_NIMCALL(void, parseheader_dvVA44pq54kR8iSXiF0Nzw)(NimStringDesc* line0, TY_wOvXi5VibnCNgN9buQRQD4A* Result);
static N_INLINE(NI, parseuntil_NGJAHkdW7mFJbCRar9a8aQwhttpcore)(NimStringDesc* s0, NimStringDesc** token0, NIM_CHAR until0, NI start0);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_UuvD8G9cNX019aF41qsh5CHQ)(TY_kN8up2W6YKc5YA9avn5mV5w* protocol0, Httpversion_QPubEzrnvJXtiz9alIdNQeA ver0);
N_NIMCALL(NIM_BOOL, contains_TqJZqI5LP2K4ETnN4c53IA)(Httpmethod_wfZHspwVKQPl9aWhkIcMrAA_Set methods0, NimStringDesc* x0);
N_NIMCALL(Httpmethod_wfZHspwVKQPl9aWhkIcMrAA, parseenum_Fate71RPNtHBz7Ge4w8uyQ)(NimStringDesc* s0);
N_NIMCALL(NimStringDesc*, HEX24_9cVsFvz7mEtKMww1u8rPboA)(NI code0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_PG9ak9auXm4C1B9cy7G8FMgAg)(NimStringDesc* rawcode0, NI code0);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s0);
N_NIMCALL(NIM_BOOL, is2xx_uF68q2LVK1IXFm3anWwLLg)(NI code0);
N_NIMCALL(NIM_BOOL, is3xx_uF68q2LVK1IXFm3anWwLLg_2)(NI code0);
N_NIMCALL(NIM_BOOL, is4xx_uF68q2LVK1IXFm3anWwLLg_3)(NI code0);
N_NIMCALL(NIM_BOOL, is5xx_uF68q2LVK1IXFm3anWwLLg_4)(NI code0);
N_NIMCALL(NimStringDesc*, HEX24_RICyMV0qYxZu9cqwCi9aeRDA)(Httpmethod_wfZHspwVKQPl9aWhkIcMrAA httpmethod0);
N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s0);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s0, Slice_qL3WGViqT0p5sVr4YFHsLg x0);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e0, TNimType* typ0);
static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, HEX2EHEX2E_18yoMoUbfoITYgEZSwZDYAtimes)(NI a0, NI b0);
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_GM611pWlOrQ7hvMPcuAACA;
extern TNimType NTI_Exo1CrLCLUIZQ4IUZ9aXEGg;
TNimType NTI_FbZeO4trJhT2CCJ9aLxejqw;
extern Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_wOvXi5VibnCNgN9buQRQD4A;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ;
TNimType NTI_29caZmiPrO6d9cg0Ucdm9bdAA;
TNimType NTI_wfZHspwVKQPl9aWhkIcMrAA;
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_8, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_9, "", 0);
static NIM_CONST TY_nmiMWKVIe46vacnhAFrQvw_Set T_Evu9b2R1utZubyCikahWx1g_18 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_31, "100 Continue", 12);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_32, "101 Switching Protocols", 23);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_33, "200 OK", 6);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_34, "201 Created", 11);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_35, "202 Accepted", 12);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_36, "203 Non-Authoritative Information", 33);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_37, "204 No Content", 14);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_38, "205 Reset Content", 17);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_39, "206 Partial Content", 19);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_40, "300 Multiple Choices", 20);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_41, "301 Moved Permanently", 21);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_42, "302 Found", 9);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_43, "303 See Other", 13);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_44, "304 Not Modified", 16);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_45, "305 Use Proxy", 13);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_46, "307 Temporary Redirect", 22);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_47, "400 Bad Request", 15);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_48, "401 Unauthorized", 16);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_49, "403 Forbidden", 13);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_50, "404 Not Found", 13);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_51, "405 Method Not Allowed", 22);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_52, "406 Not Acceptable", 18);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_53, "407 Proxy Authentication Required", 33);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_54, "408 Request Timeout", 19);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_55, "409 Conflict", 12);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_56, "410 Gone", 8);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_57, "411 Length Required", 19);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_58, "412 Precondition Failed", 23);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_59, "413 Request Entity Too Large", 28);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_60, "414 Request-URI Too Long", 24);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_61, "415 Unsupported Media Type", 26);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_62, "416 Requested Range Not Satisfiable", 35);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_63, "417 Expectation Failed", 22);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_64, "418 I\'m a teapot", 16);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_65, "421 Misdirected Request", 23);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_66, "422 Unprocessable Entity", 24);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_67, "426 Upgrade Required", 20);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_68, "428 Precondition Required", 25);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_69, "429 Too Many Requests", 21);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_70, "431 Request Header Fields Too Large", 35);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_71, "451 Unavailable For Legal Reasons", 33);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_72, "500 Internal Server Error", 25);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_73, "501 Not Implemented", 19);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_74, "502 Bad Gateway", 15);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_75, "503 Service Unavailable", 23);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_76, "504 Gateway Timeout", 19);
STRING_LITERAL(T_Evu9b2R1utZubyCikahWx1g_77, "505 HTTP Version Not Supported", 30);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode0) {
	NIM_BOOL result0;
	nimfr("isFilled", "tableimpl.nim")
	result0 = (NIM_BOOL)0;
	nimln(18, "tableimpl.nim");
	nimln(347, "system.nim");
	nimln(18, "tableimpl.nim");
	result0 = !((hcode0 == ((NI) 0)));
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, equalmem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a0, void* b0, NI size0) {
	NIM_BOOL result0;
	int LOC1;
	result0 = (NIM_BOOL)0;
	LOC1 = (int)0;
	LOC1 = memcmp(a0, b0, ((size_t) (size0)));
	result0 = (LOC1 == ((NI32) 0));
	return result0;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a0, NimStringDesc* b0) {
	NIM_BOOL result0;
	NIM_BOOL LOC11;
{	result0 = (NIM_BOOL)0;
	{
		if (!(a0 == b0)) goto LA3;
		result0 = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b0 == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = (NIM_BOOL)0;
	LOC11 = ((*a0).Sup.len == (*b0).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC11 = equalmem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a0).data)), ((void*) ((*b0).data)), ((NI) ((*a0).Sup.len)));
	LA12: ;
	result0 = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, nexttry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h0, NI maxhash0) {
	NI result0;
	NI T_Evu9b2R1utZubyCikahWx1g_2;
	nimfr("nextTry", "tableimpl.nim")
	result0 = (NI)0;
	nimln(28, "tableimpl.nim");
	T_Evu9b2R1utZubyCikahWx1g_2 = addInt(h0, ((NI) 1));
	result0 = (NI)((NI)(T_Evu9b2R1utZubyCikahWx1g_2) & maxhash0);
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, rawget_IKEP9cnFCFaJ7ddTfNBNwiAtables)(Table_LLQadDAXEvd71UDdEc3lDA t0, NimStringDesc* key0, NI* hc0) {
	NI result0;
	NI h0;
	NI T_Evu9b2R1utZubyCikahWx1g_3;
	nimfr("rawGet", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(43, "tableimpl.nim");
	(*hc0) = hash_uBstFm5SYVQeOL3j9c9bc58A(key0);
	nimln(53, "tableimpl.nim");
	{
		if (!((*hc0) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc0) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)((*hc0) & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
			LOC7 = (NIM_BOOL)0;
			LOC7 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t0.data->data[h0].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC10 = (t0.data->data[h0].Field0 == (*hc0));
				if (!(LOC10)) goto LA11;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings(t0.data->data[h0].Field1, key0);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(75, "tableimpl.nim");
	nimln(40, "tableimpl.nim");
	T_Evu9b2R1utZubyCikahWx1g_3 = subInt(((NI) -1), h0);
	result0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_3);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, rawgetknownhc_RKwyKXZlTvFd0VZfVx9bcgQtables)(Table_LLQadDAXEvd71UDdEc3lDA t0, NimStringDesc* key0, NI hc0) {
	NI result0;
	NI h0;
	NI T_Evu9b2R1utZubyCikahWx1g_4;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result0 = (NI)0;
	nimln(31, "tableimpl.nim");
	nimln(116, "tables.nim");
	h0 = (NI)(hc0 & (t0.data ? (t0.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
			LOC3 = (NIM_BOOL)0;
			LOC3 = isfilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t0.data->data[h0].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = (NIM_BOOL)0;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC6 = (t0.data->data[h0].Field0 == hc0);
				if (!(LOC6)) goto LA7;
				if ((NU)(h0) >= (NU)(t0.data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t0.data->data[h0].Field1, key0);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result0 = h0;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(116, "tables.nim");
			h0 = nexttry_OLPhxSyW9bte5CwHzzQVhfAtables(h0, (t0.data ? (t0.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(69, "tableimpl.nim");
	nimln(40, "tableimpl.nim");
	T_Evu9b2R1utZubyCikahWx1g_4 = subInt(((NI) -1), h0);
	result0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_4);
	}BeforeRet: ;
	popFrame();
	return result0;
}
static N_NIMCALL(void, Marker_TY_FbZeO4trJhT2CCJ9aLxejqw)(void* p, NI op) {
	HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* a;
	a = (HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*)p;
	nimGCvisit((void*)(*a).table, op);
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(280, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(280, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(281, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		nimln(282, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(283, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(283, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(284, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		nimln(285, "gc.nim");
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(286, "gc.nim");
			rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(287, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*, newhttpheaders_6szM8dtom9bIqki4DkcPGmg)(void) {
	HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* result0;
	nimfr("newHttpHeaders", "httpcore.nim")
	result0 = (HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*)0;
	nimln(105, "httpcore.nim");
	result0 = (HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*) newObj((&NTI_FbZeO4trJhT2CCJ9aLxejqw), sizeof(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA));
	nimln(106, "httpcore.nim");
	asgnRefNoCycle((void**) (&(*result0).table), newtable_CI6CAcgU9cmDZWyfVHj8z4g(((NI) 64)));
	popFrame();
	return result0;
}
static N_NIMCALL(void, Marker_TY_29caZmiPrO6d9cg0Ucdm9bdAA)(void* p, NI op) {
	TY_29caZmiPrO6d9cg0Ucdm9bdAA* a;
	NI LOC1;
	a = (TY_29caZmiPrO6d9cg0Ucdm9bdAA*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(262, "gc.nim");
	c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p0);
	nimln(264, "gc.nim");
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(265, "gc.nim");
		rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*, newhttpheaders_2cpWqwa9aUbsdj1oKqpSfow)(TY_UV3llMMYFckfui8YMBuUZA* keyvaluepairs0, NI keyvaluepairs0Len0) {
	HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* result0;
	TY_29caZmiPrO6d9cg0Ucdm9bdAA* pairs0;
	nimfr("newHttpHeaders", "httpcore.nim")
	result0 = (HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*)0;
	nimln(110, "httpcore.nim");
	pairs0 = (TY_29caZmiPrO6d9cg0Ucdm9bdAA*) newSeq((&NTI_29caZmiPrO6d9cg0Ucdm9bdAA), 0);
	{
		TY_UV3llMMYFckfui8YMBuUZA pair_kI3POsLAsQZUwdNk4eeoqw;
		NI i_bwWBtVAilN8uqx88s9aShrA;
		memset((void*)(&pair_kI3POsLAsQZUwdNk4eeoqw), 0, sizeof(pair_kI3POsLAsQZUwdNk4eeoqw));
		nimln(1999, "system.nim");
		i_bwWBtVAilN8uqx88s9aShrA = ((NI) 0);
		{
			nimln(2000, "system.nim");
			while (1) {
				TY_wOvXi5VibnCNgN9buQRQD4A LOC4;
				TY_nHXaesL0DJZHyVS07ARPRA LOC5;
				NimStringDesc* LOC6;
				NimStringDesc* LOC7;
				NI T_Evu9b2R1utZubyCikahWx1g_6;
				nimln(1999, "system.nim");
				nimln(111, "httpcore.nim");
				if (!(i_bwWBtVAilN8uqx88s9aShrA < keyvaluepairs0Len0)) goto LA3;
				nimln(2001, "system.nim");
				if ((NU)(i_bwWBtVAilN8uqx88s9aShrA) >= (NU)(keyvaluepairs0Len0)) raiseIndexError();
				pair_kI3POsLAsQZUwdNk4eeoqw.Field0 = keyvaluepairs0[i_bwWBtVAilN8uqx88s9aShrA].Field0;
				pair_kI3POsLAsQZUwdNk4eeoqw.Field1 = keyvaluepairs0[i_bwWBtVAilN8uqx88s9aShrA].Field1;
				nimln(112, "httpcore.nim");
				memset((void*)(&LOC4), 0, sizeof(LOC4));
				LOC4.Field0 = nsuToLowerAsciiStr(pair_kI3POsLAsQZUwdNk4eeoqw.Field0);
				LOC4.Field1 = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ), 1);
				memset((void*)LOC5, 0, sizeof(LOC5));
				LOC5[0] = copyString(pair_kI3POsLAsQZUwdNk4eeoqw.Field1);
				LOC6 = (NimStringDesc*)0;
				LOC6 = LOC4.Field1->data[0]; LOC4.Field1->data[0] = copyStringRC1(LOC5[0]);
				if (LOC6) nimGCunrefNoCycle(LOC6);
				pairs0 = (TY_29caZmiPrO6d9cg0Ucdm9bdAA*) incrSeqV2(&(pairs0)->Sup, sizeof(TY_wOvXi5VibnCNgN9buQRQD4A));
				LOC7 = (NimStringDesc*)0;
				LOC7 = pairs0->data[pairs0->Sup.len].Field0; pairs0->data[pairs0->Sup.len].Field0 = copyStringRC1(LOC4.Field0);
				if (LOC7) nimGCunrefNoCycle(LOC7);
				genericSeqAssign((&pairs0->data[pairs0->Sup.len].Field1), LOC4.Field1, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ));
				++pairs0->Sup.len;
				nimln(1999, "system.nim");
				T_Evu9b2R1utZubyCikahWx1g_6 = addInt(i_bwWBtVAilN8uqx88s9aShrA, ((NI) 1));
				i_bwWBtVAilN8uqx88s9aShrA = (NI)(T_Evu9b2R1utZubyCikahWx1g_6);
			} LA3: ;
		}
	}
	nimln(113, "httpcore.nim");
	result0 = (HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*) newObj((&NTI_FbZeO4trJhT2CCJ9aLxejqw), sizeof(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA));
	nimln(114, "httpcore.nim");
	asgnRefNoCycle((void**) (&(*result0).table), newtable_vwPfOZ6WCX1qHilQ0EWk9bQ(pairs0->data, pairs0->Sup.len));
	popFrame();
	return result0;
}

N_NIMCALL(void, clear_OorRT6sittWQ6hHggIcv7A)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0) {
	nimfr("clear", "httpcore.nim")
	nimln(117, "httpcore.nim");
	clear_axjU83goYo2deNG5N5zCTA((*headers0).table);
	popFrame();
}

N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, HEX5BHEX5D_2I7W00Lgs3jqrdJTli4b9cA)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result0;
	NimStringDesc* LOC1;
	TY_sM4lkSb7zS6F7OVMvW9cffQ** LOC2;
	nimfr("[]", "httpcore.nim")
{	result0 = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln(127, "httpcore.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = nsuToLowerAsciiStr(key0);
	LOC2 = (TY_sM4lkSb7zS6F7OVMvW9cffQ**)0;
	LOC2 = HEX5BHEX5D_Q3d9cok5U8i0JCsF7VnnIJw((*headers0).table, LOC1);
	genericSeqAssign((&result0), (*LOC2), (&NTI_sM4lkSb7zS6F7OVMvW9cffQ));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, tostring_lBEoN6A9bKNublZsSxuhYeA)(TY_sM4lkSb7zS6F7OVMvW9cffQ* values0) {
	NimStringDesc* result0;
	nimfr("toString", "httpcore.nim")
{	result0 = (NimStringDesc*)0;
	nimln(130, "httpcore.nim");
	if ((NU)(((NI) 0)) >= (NU)(values0->Sup.len)) raiseIndexError();
	result0 = copyString(values0->data[((NI) 0)]);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, HEX5BHEX5D_vxOYVkVCdrAoGHSvYOjvYA)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, NI i0) {
	NimStringDesc* result0;
	NimStringDesc* LOC1;
	TY_sM4lkSb7zS6F7OVMvW9cffQ** LOC2;
	nimfr("[]", "httpcore.nim")
{	result0 = (NimStringDesc*)0;
	nimln(136, "httpcore.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = nsuToLowerAsciiStr(key0);
	LOC2 = (TY_sM4lkSb7zS6F7OVMvW9cffQ**)0;
	LOC2 = HEX5BHEX5D_Q3d9cok5U8i0JCsF7VnnIJw((*headers0).table, LOC1);
	if ((NU)(i0) >= (NU)((*LOC2)->Sup.len)) raiseIndexError();
	result0 = copyString((*LOC2)->data[i0]);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_WBU77bh0wmagRXPlwfoQ4w)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, NimStringDesc* value0) {
	NimStringDesc* LOC1;
	TY_sM4lkSb7zS6F7OVMvW9cffQ* LOC2;
	TY_nHXaesL0DJZHyVS07ARPRA LOC3;
	NimStringDesc* LOC4;
	nimfr("[]=", "httpcore.nim")
	nimln(141, "httpcore.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = nsuToLowerAsciiStr(key0);
	LOC2 = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	LOC2 = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ), 1);
	memset((void*)LOC3, 0, sizeof(LOC3));
	LOC3[0] = copyString(value0);
	LOC4 = (NimStringDesc*)0;
	LOC4 = LOC2->data[0]; LOC2->data[0] = copyStringRC1(LOC3[0]);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	HEX5BHEX5DHEX3D_Hk6a82dIBZqReb79aiZ9czeQ((*headers0).table, LOC1, LOC2);
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_TqzBU8hdRGHa9aQu0RrPqCw)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, TY_sM4lkSb7zS6F7OVMvW9cffQ* value0) {
	NimStringDesc* LOC1;
	nimfr("[]=", "httpcore.nim")
	nimln(147, "httpcore.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = nsuToLowerAsciiStr(key0);
	HEX5BHEX5DHEX3D_Hk6a82dIBZqReb79aiZ9czeQ((*headers0).table, LOC1, value0);
	popFrame();
}

N_NIMCALL(void, add_WBU77bh0wmagRXPlwfoQ4w_2)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, NimStringDesc* value0) {
	nimfr("add", "httpcore.nim")
	nimln(152, "httpcore.nim");
	{
		NimStringDesc* LOC3;
		NIM_BOOL LOC4;
		NimStringDesc* LOC7;
		TY_sM4lkSb7zS6F7OVMvW9cffQ* LOC8;
		TY_nHXaesL0DJZHyVS07ARPRA LOC9;
		NimStringDesc* LOC10;
		LOC3 = (NimStringDesc*)0;
		LOC3 = nsuToLowerAsciiStr(key0);
		LOC4 = (NIM_BOOL)0;
		LOC4 = haskey_dVPEHWNM9ac65s5ksvHbOhg((*headers0).table, LOC3);
		if (!!(LOC4)) goto LA5;
		nimln(153, "httpcore.nim");
		LOC7 = (NimStringDesc*)0;
		LOC7 = nsuToLowerAsciiStr(key0);
		LOC8 = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		LOC8 = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ), 1);
		memset((void*)LOC9, 0, sizeof(LOC9));
		LOC9[0] = copyString(value0);
		LOC10 = (NimStringDesc*)0;
		LOC10 = LOC8->data[0]; LOC8->data[0] = copyStringRC1(LOC9[0]);
		if (LOC10) nimGCunrefNoCycle(LOC10);
		HEX5BHEX5DHEX3D_Hk6a82dIBZqReb79aiZ9czeQ((*headers0).table, LOC7, LOC8);
	}
	goto LA1;
	LA5: ;
	{
		NimStringDesc* LOC12;
		TY_sM4lkSb7zS6F7OVMvW9cffQ** LOC13;
		NimStringDesc* LOC14;
		nimln(155, "httpcore.nim");
		LOC12 = (NimStringDesc*)0;
		LOC12 = nsuToLowerAsciiStr(key0);
		LOC13 = (TY_sM4lkSb7zS6F7OVMvW9cffQ**)0;
		LOC13 = HEX5BHEX5D_Q3d9cok5U8i0JCsF7VnnIJw((*headers0).table, LOC12);
		(*LOC13) = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*LOC13))->Sup, sizeof(NimStringDesc*));
		LOC14 = (NimStringDesc*)0;
		LOC14 = (*LOC13)->data[(*LOC13)->Sup.len]; (*LOC13)->data[(*LOC13)->Sup.len] = copyStringRC1(value0);
		if (LOC14) nimGCunrefNoCycle(LOC14);
		++(*LOC13)->Sup.len;
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, del_9ctXA59cPMtAzCsUvbEbVV9bg)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0) {
	NimStringDesc* LOC1;
	nimfr("del", "httpcore.nim")
	nimln(159, "httpcore.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = nsuToLowerAsciiStr(key0);
	del_xE9c9cVqHJHvzjbqM89cWGX2w((*headers0).table, LOC1);
	popFrame();
}

N_NIMCALL(NIM_BOOL, contains_oFJPRbcAHZLz4RVXeZruJw)(TY_sM4lkSb7zS6F7OVMvW9cffQ* values0, NimStringDesc* value0) {
	NIM_BOOL result0;
	nimfr("contains", "httpcore.nim")
{	result0 = (NIM_BOOL)0;
	{
		NimStringDesc* val_9bQEVGrhUiZxDU35eJUHDjA;
		TY_sM4lkSb7zS6F7OVMvW9cffQ* HEX3Atmp_1427QxoAJPUDRe8k6RkLmA;
		NI i_6BDiR9cPOYDOF1JLvK1e5dA;
		NI L_ph3w1TTR62swJveW4bAEgQ;
		val_9bQEVGrhUiZxDU35eJUHDjA = (NimStringDesc*)0;
		HEX3Atmp_1427QxoAJPUDRe8k6RkLmA = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		nimln(170, "httpcore.nim");
		HEX3Atmp_1427QxoAJPUDRe8k6RkLmA = values0;
		nimln(3497, "system.nim");
		i_6BDiR9cPOYDOF1JLvK1e5dA = ((NI) 0);
		nimln(3498, "system.nim");
		nimln(3495, "system.nim");
		L_ph3w1TTR62swJveW4bAEgQ = (HEX3Atmp_1427QxoAJPUDRe8k6RkLmA ? HEX3Atmp_1427QxoAJPUDRe8k6RkLmA->Sup.len : 0);
		{
			nimln(3499, "system.nim");
			while (1) {
				NI T_Evu9b2R1utZubyCikahWx1g_7;
				nimln(3497, "system.nim");
				if (!(i_6BDiR9cPOYDOF1JLvK1e5dA < L_ph3w1TTR62swJveW4bAEgQ)) goto LA3;
				nimln(3500, "system.nim");
				if ((NU)(i_6BDiR9cPOYDOF1JLvK1e5dA) >= (NU)(HEX3Atmp_1427QxoAJPUDRe8k6RkLmA->Sup.len)) raiseIndexError();
				val_9bQEVGrhUiZxDU35eJUHDjA = HEX3Atmp_1427QxoAJPUDRe8k6RkLmA->data[i_6BDiR9cPOYDOF1JLvK1e5dA];
				nimln(171, "httpcore.nim");
				{
					NimStringDesc* LOC6;
					NimStringDesc* LOC7;
					LOC6 = (NimStringDesc*)0;
					LOC6 = nsuToLowerAsciiStr(val_9bQEVGrhUiZxDU35eJUHDjA);
					LOC7 = (NimStringDesc*)0;
					LOC7 = nsuToLowerAsciiStr(value0);
					if (!eqStrings(LOC6, LOC7)) goto LA8;
					result0 = NIM_TRUE;
					goto BeforeRet;
				}
				LA8: ;
				nimln(3497, "system.nim");
				T_Evu9b2R1utZubyCikahWx1g_7 = addInt(i_6BDiR9cPOYDOF1JLvK1e5dA, ((NI) 1));
				i_6BDiR9cPOYDOF1JLvK1e5dA = (NI)(T_Evu9b2R1utZubyCikahWx1g_7);
				nimln(3502, "system.nim");
				{
					nimln(3495, "system.nim");
					if (!!(((HEX3Atmp_1427QxoAJPUDRe8k6RkLmA ? HEX3Atmp_1427QxoAJPUDRe8k6RkLmA->Sup.len : 0) == L_ph3w1TTR62swJveW4bAEgQ))) goto LA12;
					nimln(3502, "system.nim");
					failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_8));
				}
				LA12: ;
			} LA3: ;
		}
	}
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, haskey_T0KkqFbqlm8065Ws4h4NSg)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0) {
	NIM_BOOL result0;
	NimStringDesc* LOC1;
	nimfr("hasKey", "httpcore.nim")
{	result0 = (NIM_BOOL)0;
	nimln(174, "httpcore.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = nsuToLowerAsciiStr(key0);
	result0 = haskey_dVPEHWNM9ac65s5ksvHbOhg((*headers0).table, LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(TY_sM4lkSb7zS6F7OVMvW9cffQ*, getordefault_iYU3axHYDC9bL2abC1Ss5fw)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0, NimStringDesc* key0, TY_sM4lkSb7zS6F7OVMvW9cffQ* default_PmXnNu6StMyVAa1WAcbs9aA) {
	TY_sM4lkSb7zS6F7OVMvW9cffQ* result0;
	nimfr("getOrDefault", "httpcore.nim")
{	result0 = (TY_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln(180, "httpcore.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = haskey_T0KkqFbqlm8065Ws4h4NSg(headers0, key0);
		if (!LOC3) goto LA4;
		nimln(181, "httpcore.nim");
		result0 = HEX5BHEX5D_2I7W00Lgs3jqrdJTli4b9cA(headers0, key0);
		goto BeforeRet;
	}
	goto LA1;
	LA4: ;
	{
		nimln(183, "httpcore.nim");
		genericSeqAssign((&result0), default_PmXnNu6StMyVAa1WAcbs9aA, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ));
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, len_KJLsaxEBMwC7Zow21T6yQA)(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA* headers0) {
	NI result0;
	nimfr("len", "httpcore.nim")
{	result0 = (NI)0;
	nimln(185, "httpcore.nim");
	result0 = len_gPutmFMjF2dpNdfOqcokuQ((*headers0).table);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, skipwhitespace_eRDxv9ah1K9c5mDt1GmbdF9aghttpcore)(NimStringDesc* s0, NI start0) {
	NI result0;
	nimfr("skipWhitespace", "parseutils.nim")
	result0 = (NI)0;
	{
		nimln(125, "parseutils.nim");
		while (1) {
			NI T_Evu9b2R1utZubyCikahWx1g_11;
			NI T_Evu9b2R1utZubyCikahWx1g_12;
			T_Evu9b2R1utZubyCikahWx1g_11 = addInt(start0, result0);
			if ((NU)((NI)(T_Evu9b2R1utZubyCikahWx1g_11)) > (NU)(s0->Sup.len)) raiseIndexError();
			if (!(((NU8)(s0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_11)])) == ((NU8)(32)) || ((NU8)(s0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_11)])) == ((NU8)(9)) || ((NU8)(s0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_11)])) == ((NU8)(11)) || ((NU8)(s0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_11)])) == ((NU8)(13)) || ((NU8)(s0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_11)])) == ((NU8)(10)) || ((NU8)(s0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_11)])) == ((NU8)(12)))) goto LA2;
			T_Evu9b2R1utZubyCikahWx1g_12 = addInt(result0, ((NI) 1));
			result0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_12);
		} LA2: ;
	}
	popFrame();
	return result0;
}

static N_INLINE(NI, parseuntil_zSglkPmqQkVaLkVSiDuiCguri)(NimStringDesc* s0, NimStringDesc** token0, TY_nmiMWKVIe46vacnhAFrQvw_Set until0, NI start0) {
	NI result0;
	NI i0;
	NI T_Evu9b2R1utZubyCikahWx1g_16;
	NI T_Evu9b2R1utZubyCikahWx1g_17;
	nimfr("parseUntil", "parseutils.nim")
	result0 = (NI)0;
	nimln(161, "parseutils.nim");
	i0 = start0;
	{
		nimln(162, "parseutils.nim");
		while (1) {
			NIM_BOOL LOC3;
			NI T_Evu9b2R1utZubyCikahWx1g_15;
			LOC3 = (NIM_BOOL)0;
			LOC3 = (i0 < (s0 ? s0->Sup.len : 0));
			if (!(LOC3)) goto LA4;
			nimln(1130, "system.nim");
			nimln(162, "parseutils.nim");
			if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
			LOC3 = !(((until0[(NU)(((NU8)(s0->data[i0])))>>3] &(1U<<((NU)(((NU8)(s0->data[i0])))&7U)))!=0));
			LA4: ;
			if (!LOC3) goto LA2;
			T_Evu9b2R1utZubyCikahWx1g_15 = addInt(i0, ((NI) 1));
			i0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_15);
		} LA2: ;
	}
	nimln(163, "parseutils.nim");
	T_Evu9b2R1utZubyCikahWx1g_16 = subInt(i0, start0);
	result0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_16);
	nimln(164, "parseutils.nim");
	T_Evu9b2R1utZubyCikahWx1g_17 = subInt(i0, ((NI) 1));
	unsureAsgnRef((void**) (&(*token0)), copyStrLast(s0, start0, (NI)(T_Evu9b2R1utZubyCikahWx1g_17)));
	popFrame();
	return result0;
}

N_NIMCALL(NI, parselist_ezobL19b9cekPtKoupwBaGvA)(NimStringDesc* line0, TY_sM4lkSb7zS6F7OVMvW9cffQ** list0, NI start0) {
	NI result0;
	NI i0;
	NimStringDesc* current0;
	nimfr("parseList", "httpcore.nim")
	result0 = (NI)0;
	nimln(188, "httpcore.nim");
	i0 = ((NI) 0);
	nimln(189, "httpcore.nim");
	current0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_9));
	{
		nimln(190, "httpcore.nim");
		while (1) {
			NI T_Evu9b2R1utZubyCikahWx1g_10;
			NI T_Evu9b2R1utZubyCikahWx1g_13;
			NI LOC3;
			NI T_Evu9b2R1utZubyCikahWx1g_14;
			NI T_Evu9b2R1utZubyCikahWx1g_19;
			NI LOC4;
			NI T_Evu9b2R1utZubyCikahWx1g_20;
			NimStringDesc* LOC5;
			nimln(1130, "system.nim");
			nimln(190, "httpcore.nim");
			T_Evu9b2R1utZubyCikahWx1g_10 = addInt(start0, i0);
			if ((NU)((NI)(T_Evu9b2R1utZubyCikahWx1g_10)) > (NU)(line0->Sup.len)) raiseIndexError();
			if (!!((((NU8)(line0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_10)])) == ((NU8)(13)) || ((NU8)(line0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_10)])) == ((NU8)(10)) || ((NU8)(line0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_10)])) == ((NU8)(0))))) goto LA2;
			nimln(191, "httpcore.nim");
			T_Evu9b2R1utZubyCikahWx1g_13 = addInt(start0, i0);
			LOC3 = (NI)0;
			LOC3 = skipwhitespace_eRDxv9ah1K9c5mDt1GmbdF9aghttpcore(line0, (NI)(T_Evu9b2R1utZubyCikahWx1g_13));
			T_Evu9b2R1utZubyCikahWx1g_14 = addInt(i0, LOC3);
			i0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_14);
			nimln(192, "httpcore.nim");
			T_Evu9b2R1utZubyCikahWx1g_19 = addInt(start0, i0);
			LOC4 = (NI)0;
			LOC4 = parseuntil_zSglkPmqQkVaLkVSiDuiCguri(line0, (&current0), T_Evu9b2R1utZubyCikahWx1g_18, (NI)(T_Evu9b2R1utZubyCikahWx1g_19));
			T_Evu9b2R1utZubyCikahWx1g_20 = addInt(i0, LOC4);
			i0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_20);
			nimln(193, "httpcore.nim");
			(*list0) = (TY_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*list0))->Sup, sizeof(NimStringDesc*));
			LOC5 = (NimStringDesc*)0;
			LOC5 = (*list0)->data[(*list0)->Sup.len]; (*list0)->data[(*list0)->Sup.len] = copyStringRC1(current0);
			if (LOC5) nimGCunrefNoCycle(LOC5);
			++(*list0)->Sup.len;
			nimln(194, "httpcore.nim");
			{
				NI T_Evu9b2R1utZubyCikahWx1g_21;
				NI T_Evu9b2R1utZubyCikahWx1g_22;
				T_Evu9b2R1utZubyCikahWx1g_21 = addInt(start0, i0);
				if ((NU)((NI)(T_Evu9b2R1utZubyCikahWx1g_21)) > (NU)(line0->Sup.len)) raiseIndexError();
				if (!((NU8)(line0->data[(NI)(T_Evu9b2R1utZubyCikahWx1g_21)]) == (NU8)(44))) goto LA8;
				nimln(195, "httpcore.nim");
				T_Evu9b2R1utZubyCikahWx1g_22 = addInt(i0, ((NI) 1));
				i0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_22);
			}
			LA8: ;
			nimln(196, "httpcore.nim");
			current0 = setLengthStr(current0, ((NI) 0));
		} LA2: ;
	}
	popFrame();
	return result0;
}

static N_INLINE(NI, parseuntil_NGJAHkdW7mFJbCRar9a8aQwhttpcore)(NimStringDesc* s0, NimStringDesc** token0, NIM_CHAR until0, NI start0) {
	NI result0;
	NI i0;
	NI T_Evu9b2R1utZubyCikahWx1g_24;
	NI T_Evu9b2R1utZubyCikahWx1g_25;
	nimfr("parseUntil", "parseutils.nim")
	result0 = (NI)0;
	nimln(171, "parseutils.nim");
	i0 = start0;
	{
		nimln(172, "parseutils.nim");
		while (1) {
			NIM_BOOL LOC3;
			NI T_Evu9b2R1utZubyCikahWx1g_23;
			LOC3 = (NIM_BOOL)0;
			LOC3 = (i0 < (s0 ? s0->Sup.len : 0));
			if (!(LOC3)) goto LA4;
			nimln(347, "system.nim");
			nimln(172, "parseutils.nim");
			if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
			LOC3 = !(((NU8)(s0->data[i0]) == (NU8)(until0)));
			LA4: ;
			if (!LOC3) goto LA2;
			T_Evu9b2R1utZubyCikahWx1g_23 = addInt(i0, ((NI) 1));
			i0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_23);
		} LA2: ;
	}
	nimln(173, "parseutils.nim");
	T_Evu9b2R1utZubyCikahWx1g_24 = subInt(i0, start0);
	result0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_24);
	nimln(174, "parseutils.nim");
	T_Evu9b2R1utZubyCikahWx1g_25 = subInt(i0, ((NI) 1));
	unsureAsgnRef((void**) (&(*token0)), copyStrLast(s0, start0, (NI)(T_Evu9b2R1utZubyCikahWx1g_25)));
	popFrame();
	return result0;
}

N_NIMCALL(void, parseheader_dvVA44pq54kR8iSXiF0Nzw)(NimStringDesc* line0, TY_wOvXi5VibnCNgN9buQRQD4A* Result) {
	NI i0;
	NI T_Evu9b2R1utZubyCikahWx1g_26;
	nimfr("parseHeader", "httpcore.nim")
	nimln(203, "httpcore.nim");
	unsureAsgnRef((void**) (&(*Result).Field1), (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ), 0));
	nimln(204, "httpcore.nim");
	i0 = ((NI) 0);
	nimln(205, "httpcore.nim");
	i0 = parseuntil_NGJAHkdW7mFJbCRar9a8aQwhttpcore(line0, (&(*Result).Field0), 58, ((NI) 0));
	nimln(206, "httpcore.nim");
	T_Evu9b2R1utZubyCikahWx1g_26 = addInt(i0, ((NI) 1));
	i0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_26);
	nimln(207, "httpcore.nim");
	{
		NI LOC5;
		NI T_Evu9b2R1utZubyCikahWx1g_27;
		if (!(i0 < (line0 ? line0->Sup.len : 0))) goto LA3;
		nimln(208, "httpcore.nim");
		LOC5 = (NI)0;
		LOC5 = parselist_ezobL19b9cekPtKoupwBaGvA(line0, (&(*Result).Field1), i0);
		T_Evu9b2R1utZubyCikahWx1g_27 = addInt(i0, LOC5);
		i0 = (NI)(T_Evu9b2R1utZubyCikahWx1g_27);
	}
	goto LA1;
	LA3: ;
	{
		nimln(210, "httpcore.nim");
		unsureAsgnRef((void**) (&(*Result).Field1), (TY_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ), 0));
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, HEX3DHEX3D_UuvD8G9cNX019aF41qsh5CHQ)(TY_kN8up2W6YKc5YA9avn5mV5w* protocol0, Httpversion_QPubEzrnvJXtiz9alIdNQeA ver0) {
	NIM_BOOL result0;
	NI major0;
	NI minor0;
	NIM_BOOL LOC4;
	nimfr("==", "httpcore.nim")
	result0 = (NIM_BOOL)0;
	nimln(214, "httpcore.nim");
	nimln(215, "httpcore.nim");
	switch (ver0) {
	case ((Httpversion_QPubEzrnvJXtiz9alIdNQeA) 0):
	case ((Httpversion_QPubEzrnvJXtiz9alIdNQeA) 1):
	{
		major0 = ((NI) 1);
	}
	break;
	}
	nimln(217, "httpcore.nim");
	nimln(218, "httpcore.nim");
	switch (ver0) {
	case ((Httpversion_QPubEzrnvJXtiz9alIdNQeA) 0):
	{
		minor0 = ((NI) 1);
	}
	break;
	case ((Httpversion_QPubEzrnvJXtiz9alIdNQeA) 1):
	{
		minor0 = ((NI) 0);
	}
	break;
	}
	nimln(221, "httpcore.nim");
	LOC4 = (NIM_BOOL)0;
	LOC4 = ((*protocol0).Field1 == major0);
	if (!(LOC4)) goto LA5;
	LOC4 = ((*protocol0).Field2 == minor0);
	LA5: ;
	result0 = LOC4;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, contains_TqJZqI5LP2K4ETnN4c53IA)(Httpmethod_wfZHspwVKQPl9aWhkIcMrAA_Set methods0, NimStringDesc* x0) {
	NIM_BOOL result0;
	Httpmethod_wfZHspwVKQPl9aWhkIcMrAA LOC1;
	nimfr("contains", "httpcore.nim")
{	result0 = (NIM_BOOL)0;
	nimln(224, "httpcore.nim");
	LOC1 = (Httpmethod_wfZHspwVKQPl9aWhkIcMrAA)0;
	LOC1 = parseenum_Fate71RPNtHBz7Ge4w8uyQ(x0);
	result0 = ((methods0 &(1U<<((NU)(LOC1)&15U)))!=0);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, HEX24_9cVsFvz7mEtKMww1u8rPboA)(NI code0) {
	NimStringDesc* result0;
	nimfr("$", "httpcore.nim")
	result0 = (NimStringDesc*)0;
	nimln(227, "httpcore.nim");
	nimln(233, "httpcore.nim");
	switch (((NI) (code0))) {
	case ((NI) 100):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_31));
	}
	break;
	case ((NI) 101):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_32));
	}
	break;
	case ((NI) 200):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_33));
	}
	break;
	case ((NI) 201):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_34));
	}
	break;
	case ((NI) 202):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_35));
	}
	break;
	case ((NI) 203):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_36));
	}
	break;
	case ((NI) 204):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_37));
	}
	break;
	case ((NI) 205):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_38));
	}
	break;
	case ((NI) 206):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_39));
	}
	break;
	case ((NI) 300):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_40));
	}
	break;
	case ((NI) 301):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_41));
	}
	break;
	case ((NI) 302):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_42));
	}
	break;
	case ((NI) 303):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_43));
	}
	break;
	case ((NI) 304):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_44));
	}
	break;
	case ((NI) 305):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_45));
	}
	break;
	case ((NI) 307):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_46));
	}
	break;
	case ((NI) 400):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_47));
	}
	break;
	case ((NI) 401):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_48));
	}
	break;
	case ((NI) 403):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_49));
	}
	break;
	case ((NI) 404):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_50));
	}
	break;
	case ((NI) 405):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_51));
	}
	break;
	case ((NI) 406):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_52));
	}
	break;
	case ((NI) 407):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_53));
	}
	break;
	case ((NI) 408):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_54));
	}
	break;
	case ((NI) 409):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_55));
	}
	break;
	case ((NI) 410):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_56));
	}
	break;
	case ((NI) 411):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_57));
	}
	break;
	case ((NI) 412):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_58));
	}
	break;
	case ((NI) 413):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_59));
	}
	break;
	case ((NI) 414):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_60));
	}
	break;
	case ((NI) 415):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_61));
	}
	break;
	case ((NI) 416):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_62));
	}
	break;
	case ((NI) 417):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_63));
	}
	break;
	case ((NI) 418):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_64));
	}
	break;
	case ((NI) 421):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_65));
	}
	break;
	case ((NI) 422):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_66));
	}
	break;
	case ((NI) 426):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_67));
	}
	break;
	case ((NI) 428):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_68));
	}
	break;
	case ((NI) 429):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_69));
	}
	break;
	case ((NI) 431):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_70));
	}
	break;
	case ((NI) 451):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_71));
	}
	break;
	case ((NI) 500):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_72));
	}
	break;
	case ((NI) 501):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_73));
	}
	break;
	case ((NI) 502):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_74));
	}
	break;
	case ((NI) 503):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_75));
	}
	break;
	case ((NI) 504):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_76));
	}
	break;
	case ((NI) 505):
	{
		result0 = copyString(((NimStringDesc*) &T_Evu9b2R1utZubyCikahWx1g_77));
	}
	break;
	default:
	{
		nimln(281, "httpcore.nim");
		result0 = nimIntToStr(((NI) (code0)));
	}
	break;
	}
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX3D_PG9ak9auXm4C1B9cy7G8FMgAg)(NimStringDesc* rawcode0, NI code0) {
	NIM_BOOL result0;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	nimfr("==", "httpcore.nim")
{	result0 = (NIM_BOOL)0;
	nimln(286, "httpcore.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = nsuToLowerStr(rawcode0);
	LOC2 = (NimStringDesc*)0;
	LOC2 = HEX24_9cVsFvz7mEtKMww1u8rPboA(code0);
	LOC3 = (NimStringDesc*)0;
	LOC3 = nsuToLowerStr(LOC2);
	result0 = eqStrings(LOC1, LOC3);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, is2xx_uF68q2LVK1IXFm3anWwLLg)(NI code0) {
	NIM_BOOL result0;
	nimfr("is2xx", "httpcore.nim")
{	result0 = (NIM_BOOL)0;
	nimln(290, "httpcore.nim");
	result0 = (((NI) (code0)) >= ((NI) 200) && ((NI) (code0)) <= ((NI) 299));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, is3xx_uF68q2LVK1IXFm3anWwLLg_2)(NI code0) {
	NIM_BOOL result0;
	nimfr("is3xx", "httpcore.nim")
{	result0 = (NIM_BOOL)0;
	nimln(294, "httpcore.nim");
	result0 = (((NI) (code0)) >= ((NI) 300) && ((NI) (code0)) <= ((NI) 399));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, is4xx_uF68q2LVK1IXFm3anWwLLg_3)(NI code0) {
	NIM_BOOL result0;
	nimfr("is4xx", "httpcore.nim")
{	result0 = (NIM_BOOL)0;
	nimln(298, "httpcore.nim");
	result0 = (((NI) (code0)) >= ((NI) 400) && ((NI) (code0)) <= ((NI) 499));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, is5xx_uF68q2LVK1IXFm3anWwLLg_4)(NI code0) {
	NIM_BOOL result0;
	nimfr("is5xx", "httpcore.nim")
{	result0 = (NIM_BOOL)0;
	nimln(302, "httpcore.nim");
	result0 = (((NI) (code0)) >= ((NI) 500) && ((NI) (code0)) <= ((NI) 599));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s0, Slice_qL3WGViqT0p5sVr4YFHsLg x0) {
	NimStringDesc* result0;
	nimfr("[]", "system.nim")
	result0 = (NimStringDesc*)0;
	nimln(3262, "system.nim");
	result0 = copyStrLast(s0, x0.a, x0.b);
	popFrame();
	return result0;
}

static N_INLINE(Slice_qL3WGViqT0p5sVr4YFHsLg, HEX2EHEX2E_18yoMoUbfoITYgEZSwZDYAtimes)(NI a0, NI b0) {
	Slice_qL3WGViqT0p5sVr4YFHsLg result0;
	nimfr("..", "system.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(274, "system.nim");
	result0.a = a0;
	nimln(275, "system.nim");
	result0.b = b0;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, HEX24_RICyMV0qYxZu9cqwCi9aeRDA)(Httpmethod_wfZHspwVKQPl9aWhkIcMrAA httpmethod0) {
	NimStringDesc* result0;
	NI T_Evu9b2R1utZubyCikahWx1g_78;
	Slice_qL3WGViqT0p5sVr4YFHsLg LOC1;
	NimStringDesc* LOC2;
	nimfr("$", "httpcore.nim")
{	result0 = (NimStringDesc*)0;
	nimln(305, "httpcore.nim");
	T_Evu9b2R1utZubyCikahWx1g_78 = subInt((reprEnum((NI)httpmethod0, (&NTI_wfZHspwVKQPl9aWhkIcMrAA)) ? reprEnum((NI)httpmethod0, (&NTI_wfZHspwVKQPl9aWhkIcMrAA))->Sup.len : 0), ((NI) 1));
	LOC1 = HEX2EHEX2E_18yoMoUbfoITYgEZSwZDYAtimes(((NI) 4), (NI)(T_Evu9b2R1utZubyCikahWx1g_78));
	LOC2 = (NimStringDesc*)0;
	LOC2 = HEX5BHEX5D_Sq9b57KCLKZryBwyHy49aBswsystem(reprEnum((NI)httpmethod0, (&NTI_wfZHspwVKQPl9aWhkIcMrAA)), LOC1);
	result0 = nsuToUpperStr(LOC2);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_httpcoreInit000)(void) {
	nimfr("httpcore", "httpcore.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_httpcoreDatInit000)(void) {
static TNimNode* T_Evu9b2R1utZubyCikahWx1g_5[2];
static TNimNode* T_Evu9b2R1utZubyCikahWx1g_28[9];
NI T_Evu9b2R1utZubyCikahWx1g_30;
static char* NIM_CONST T_Evu9b2R1utZubyCikahWx1g_29[9] = {
"HttpHead", 
"HttpGet", 
"HttpPost", 
"HttpPut", 
"HttpDelete", 
"HttpTrace", 
"HttpOptions", 
"HttpConnect", 
"HttpPatch"};
static TNimNode T_Evu9b2R1utZubyCikahWx1g_0[14];
NTI_GM611pWlOrQ7hvMPcuAACA.size = sizeof(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA);
NTI_GM611pWlOrQ7hvMPcuAACA.kind = 18;
NTI_GM611pWlOrQ7hvMPcuAACA.base = 0;
NTI_GM611pWlOrQ7hvMPcuAACA.flags = 2;
T_Evu9b2R1utZubyCikahWx1g_0[0].kind = 1;
T_Evu9b2R1utZubyCikahWx1g_0[0].offset = offsetof(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA, table);
T_Evu9b2R1utZubyCikahWx1g_0[0].typ = (&NTI_Exo1CrLCLUIZQ4IUZ9aXEGg);
T_Evu9b2R1utZubyCikahWx1g_0[0].name = "table";
NTI_GM611pWlOrQ7hvMPcuAACA.node = &T_Evu9b2R1utZubyCikahWx1g_0[0];
NTI_FbZeO4trJhT2CCJ9aLxejqw.size = sizeof(HttpheadersHEX3Aobjecttype_GM611pWlOrQ7hvMPcuAACA*);
NTI_FbZeO4trJhT2CCJ9aLxejqw.kind = 22;
NTI_FbZeO4trJhT2CCJ9aLxejqw.base = (&NTI_GM611pWlOrQ7hvMPcuAACA);
NTI_FbZeO4trJhT2CCJ9aLxejqw.flags = 2;
NTI_FbZeO4trJhT2CCJ9aLxejqw.marker = Marker_TY_FbZeO4trJhT2CCJ9aLxejqw;
NTI_wOvXi5VibnCNgN9buQRQD4A.size = sizeof(TY_wOvXi5VibnCNgN9buQRQD4A);
NTI_wOvXi5VibnCNgN9buQRQD4A.kind = 18;
NTI_wOvXi5VibnCNgN9buQRQD4A.base = 0;
NTI_wOvXi5VibnCNgN9buQRQD4A.flags = 2;
T_Evu9b2R1utZubyCikahWx1g_5[0] = &T_Evu9b2R1utZubyCikahWx1g_0[2];
T_Evu9b2R1utZubyCikahWx1g_0[2].kind = 1;
T_Evu9b2R1utZubyCikahWx1g_0[2].offset = offsetof(TY_wOvXi5VibnCNgN9buQRQD4A, Field0);
T_Evu9b2R1utZubyCikahWx1g_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg);
T_Evu9b2R1utZubyCikahWx1g_0[2].name = "Field0";
T_Evu9b2R1utZubyCikahWx1g_5[1] = &T_Evu9b2R1utZubyCikahWx1g_0[3];
T_Evu9b2R1utZubyCikahWx1g_0[3].kind = 1;
T_Evu9b2R1utZubyCikahWx1g_0[3].offset = offsetof(TY_wOvXi5VibnCNgN9buQRQD4A, Field1);
T_Evu9b2R1utZubyCikahWx1g_0[3].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ);
T_Evu9b2R1utZubyCikahWx1g_0[3].name = "Field1";
T_Evu9b2R1utZubyCikahWx1g_0[1].len = 2; T_Evu9b2R1utZubyCikahWx1g_0[1].kind = 2; T_Evu9b2R1utZubyCikahWx1g_0[1].sons = &T_Evu9b2R1utZubyCikahWx1g_5[0];
NTI_wOvXi5VibnCNgN9buQRQD4A.node = &T_Evu9b2R1utZubyCikahWx1g_0[1];
NTI_29caZmiPrO6d9cg0Ucdm9bdAA.size = sizeof(TY_29caZmiPrO6d9cg0Ucdm9bdAA*);
NTI_29caZmiPrO6d9cg0Ucdm9bdAA.kind = 24;
NTI_29caZmiPrO6d9cg0Ucdm9bdAA.base = (&NTI_wOvXi5VibnCNgN9buQRQD4A);
NTI_29caZmiPrO6d9cg0Ucdm9bdAA.flags = 2;
NTI_29caZmiPrO6d9cg0Ucdm9bdAA.marker = Marker_TY_29caZmiPrO6d9cg0Ucdm9bdAA;
NTI_wfZHspwVKQPl9aWhkIcMrAA.size = sizeof(Httpmethod_wfZHspwVKQPl9aWhkIcMrAA);
NTI_wfZHspwVKQPl9aWhkIcMrAA.kind = 14;
NTI_wfZHspwVKQPl9aWhkIcMrAA.base = 0;
NTI_wfZHspwVKQPl9aWhkIcMrAA.flags = 3;
for (T_Evu9b2R1utZubyCikahWx1g_30 = 0; T_Evu9b2R1utZubyCikahWx1g_30 < 9; T_Evu9b2R1utZubyCikahWx1g_30++) {
T_Evu9b2R1utZubyCikahWx1g_0[T_Evu9b2R1utZubyCikahWx1g_30+4].kind = 1;
T_Evu9b2R1utZubyCikahWx1g_0[T_Evu9b2R1utZubyCikahWx1g_30+4].offset = T_Evu9b2R1utZubyCikahWx1g_30;
T_Evu9b2R1utZubyCikahWx1g_0[T_Evu9b2R1utZubyCikahWx1g_30+4].name = T_Evu9b2R1utZubyCikahWx1g_29[T_Evu9b2R1utZubyCikahWx1g_30];
T_Evu9b2R1utZubyCikahWx1g_28[T_Evu9b2R1utZubyCikahWx1g_30] = &T_Evu9b2R1utZubyCikahWx1g_0[T_Evu9b2R1utZubyCikahWx1g_30+4];
}
T_Evu9b2R1utZubyCikahWx1g_0[13].len = 9; T_Evu9b2R1utZubyCikahWx1g_0[13].kind = 2; T_Evu9b2R1utZubyCikahWx1g_0[13].sons = &T_Evu9b2R1utZubyCikahWx1g_28[0];
NTI_wfZHspwVKQPl9aWhkIcMrAA.node = &T_Evu9b2R1utZubyCikahWx1g_0[13];
}

